const DATA = [
{ id:"csharp", title:"C# aur OOPs", note:"Har interview yahin se shuru hota hai. Definition nahi — apne code ka example ready rakho.", groups:[
  { g:".NET platform basics", items:[
    ".NET Framework vs .NET Core vs .NET 5/6/8 — difference",
    "CLR kya hai, managed vs unmanaged code",
    "IL (Intermediate Language) aur JIT compilation",
    "CTS aur CLS ka matlab",
    "Assembly, DLL vs EXE, GAC",
    "Namespace vs Assembly",
    "Just-in-time vs Ahead-of-time compilation",
    ".NET Standard kya tha aur ab kyun relevant nahi"
  ]},
  { g:"OOPs pillars", items:[
    "Abstraction, Encapsulation, Inheritance, Polymorphism — har ek ka real example",
    "Abstract class vs Interface — kab kaunsa, aur kyun",
    "Method Overloading vs Overriding (compile-time vs runtime binding)",
    "virtual / override / new keyword ka farak",
    "Sealed class, static class, partial class",
    "Multiple inheritance C# mein kyun nahi — interface se kaise solve hota hai",
    "SOLID — paanchon principle, ek-ek line ka apna example"
  ]},
  { g:"Language fundamentals", items:[
    "Value type vs Reference type, Stack vs Heap",
    "Boxing aur Unboxing — performance impact",
    "const vs readonly vs static readonly",
    "string immutable kyun hai, StringBuilder kab use karein",
    "== vs .Equals() vs ReferenceEquals",
    "Access modifiers: public, private, protected, internal, protected internal",
    "Nullable types, null-coalescing (??), null-conditional (?.)",
    "var vs dynamic vs object",
    "ref vs out vs in parameters",
    "Struct vs Class — kab struct use karein",
    "Static constructor kab chalta hai",
    "Enum aur uska underlying type",
    "Indexer kya hota hai",
    "Extension method — kaise banate hain, restriction kya hai",
    "Anonymous type, Tuple, ValueTuple",
    "Record type (C# 9+) — class se kaise alag",
    "Shallow copy vs Deep copy",
    "Operator overloading",
    "Reflection kya hai, kahan use hoti hai",
    "Attributes — built-in aur custom",
    "Pattern matching, switch expression",
    "String interpolation vs concatenation vs String.Format",
    "Covariance aur Contravariance (basic idea)"
  ]},
  { g:"Collections aur Generics", items:[
    "Array vs List vs Dictionary vs HashSet — kab kya",
    "Dictionary lookup O(1) kaise — internally hashing",
    "IEnumerable vs ICollection vs IList",
    "Generics kyun — type safety aur boxing se bachav",
    "Delegate, Func, Action, Predicate",
    "Events aur delegate ka relation",
    "Lambda expression aur closure",
    "Multicast delegate",
    "Array vs ArrayList vs List — generic kyun better",
    "Stack vs Queue — LIFO/FIFO use cases",
    "IEnumerable vs IEnumerator — internally foreach kaise chalta hai",
    "yield return aur lazy iterator",
    "SortedList, SortedDictionary, ConcurrentDictionary",
    "Time complexity: List.Contains vs HashSet.Contains"
  ]},
  { g:"Memory aur exceptions", items:[
    "Garbage Collection — Gen 0, 1, 2 kaise kaam karti hain",
    "IDisposable, using block, Dispose vs Finalize",
    "Memory leak C# mein kaise hota hai (event handlers, static refs)",
    "try-catch-finally, custom exception class",
    "throw vs throw ex — stack trace ka farak"
  ]},
  { g:"Async aur threading", items:[
    "async/await internally kya karta hai (state machine, thread release)",
    "Task vs Thread vs ThreadPool",
    ".Result / .Wait() se deadlock kyun hota hai",
    "async void kyun avoid karna chahiye",
    "Task.Run kab use karein aur kab nahi",
    "CancellationToken ka use",
    "lock, Monitor, thread-safe collections",
    "Task.WhenAll vs Task.WhenAny",
    "Parallel.For / Parallel.ForEach aur PLINQ",
    "Race condition aur deadlock ka difference",
    "IAsyncEnumerable aur await foreach",
    "Synchronous code ko async mein convert karne ke rules"
  ]}
]},

{ id:"aspnet", title:"ASP.NET Core", note:"Request flow poora bolna aana chahiye — Kestrel se DB tak aur wapas.", groups:[
  { g:"Request pipeline", items:[
    "Poora flow: Kestrel → Middleware → Routing → Model Binding → Filters → Controller → Service → DB → Response",
    "Middleware kya hai, custom middleware kaise likhte ho",
    "app.Use vs app.Run vs app.Map",
    "Middleware ka order kyun matter karta hai (Authentication vs Authorization)",
    "Filters ke types: Authorization, Resource, Action, Exception, Result",
    "Middleware vs Filter — difference",
    "Program.cs / Startup.cs — ConfigureServices vs Configure",
    "Kestrel kya hai, IIS ke saath reverse proxy setup",
    "In-process vs Out-of-process hosting",
    "wwwroot aur static files middleware",
    "Minimal API vs Controller-based API"
  ]},
  { g:"MVC aur Web API essentials", items:[
    "MVC vs Web API — difference aur kab kya",
    "Controller, Action, IActionResult ke types (Ok, NotFound, BadRequest)",
    "Attribute routing vs Conventional routing",
    "Model Binding kaise kaam karti hai ([FromBody], [FromQuery], [FromRoute])",
    "ViewBag vs ViewData vs TempData vs Session (MVC)",
    "Partial View aur Razor basics",
    "Swagger / OpenAPI setup aur uska fayda",
    "File upload API kaise banate ho",
    "Async controller action ka fayda",
    "MVC request lifecycle: Browser → Routing → Controller → Action → Model → View/JsonResult → Response",
    "HTML Helpers (Html.TextBoxFor, Html.LabelFor)",
    "Version awareness: .NET Framework 4.8, Core 3.1, .NET 6/8, MVC 5, VS 2022 — tum kaunse pe ho aur kyun"
  ]},
  { g:"Caching, background work, testing", items:[
    "IMemoryCache vs IDistributedCache (Redis)",
    "Response caching aur cache headers",
    "IHostedService / BackgroundService se background job",
    "Health checks endpoint",
    "Unit testing — xUnit / NUnit basics",
    "Moq se dependency mock karna",
    "Unit test vs Integration test",
    "Testable code kaise likhte hain (DI ka role)"
  ]},
  { g:"Dependency Injection", items:[
    "DI kya hai aur kyun — loose coupling, testability",
    "Singleton vs Scoped vs Transient (yeh pakka poochha jayega)",
    "Captive dependency — Singleton mein Scoped inject karne pe kya hota hai",
    "Constructor injection vs property injection",
    "IServiceCollection mein service register karna",
    "Built-in DI container vs Autofac / third-party"
  ]},
  { g:"API design", items:[
    "REST principles, resource naming",
    "HTTP verbs: GET, POST, PUT, PATCH, DELETE — idempotency",
    "Status codes: 200, 201, 204, 400, 401, 403, 404, 409, 500",
    "PUT vs PATCH ka farak",
    "API versioning ke tareeke",
    "Model validation, DataAnnotations, ModelState",
    "DTO kyun use karte hain, entity direct return kyun nahi",
    "Global exception handling middleware",
    "CORS kya hai aur kyun chahiye",
    "Pagination, filtering, sorting API mein kaise dete ho",
    "Content negotiation aur JSON serialization settings",
    "AutoMapper ya manual mapping — trade-off",
    "Rate limiting API pe kaise lagate ho",
    "HttpClient vs IHttpClientFactory — socket exhaustion problem",
    "Third-party API call — token / API key handling, retry, timeout",
    "Serialization aur Deserialization — JSON to object aur wapas",
    "System.Text.Json vs Newtonsoft.Json",
    "Connection string aur secrets kahan rakhte ho (env, Key Vault) — hardcode kyun nahi",
    "Layered folder structure: Controller → Service → Repository → Model/DTO",
    "DTO aur loose coupling ka relation"
  ]},
  { g:"Auth aur config", items:[
    "JWT kaise kaam karta hai — header, payload, signature",
    "JWT vs Session-based auth",
    "Authentication vs Authorization",
    "Refresh token ka purpose",
    "Role-based vs Claims-based vs Policy-based authorization",
    "appsettings.json, environment-based config, IOptions pattern",
    "Logging — ILogger, structured logging, log levels"
  ]}
]},

{ id:"ef", title:"Entity Framework Core aur LINQ", note:"IQueryable vs IEnumerable ka answer galat gaya to backend round wahin khatam.", groups:[
  { g:"LINQ", items:[
    "IEnumerable vs IQueryable — memory filter vs DB SQL",
    "Deferred (lazy) execution kya hai",
    "First vs FirstOrDefault vs Single vs SingleOrDefault",
    "Where, Select, GroupBy, OrderBy, Join, Any, All, Sum, Aggregate",
    "SelectMany kab use hota hai",
    "Method syntax vs Query syntax",
    "Take, Skip — pagination ke liye",
    "Distinct, Except, Intersect, Union",
    "ToList / ToArray / ToDictionary — execution force karna",
    "Let aur multiple from clause",
    "Join vs GroupJoin vs left join in LINQ",
    "LINQ query jo DB pe translate nahi hoti — client-side evaluation ka danger"
  ]},
  { g:"EF Core", items:[
    "DbContext ka lifetime kyun Scoped hona chahiye",
    "Lazy loading vs Eager loading vs Explicit loading",
    "Include aur ThenInclude",
    "N+1 query problem — pehchanna aur fix karna",
    "AsNoTracking() kab aur kyun",
    "Change tracking kaise kaam karta hai",
    "Migrations — Add-Migration, Update-Database, rollback",
    "Code First vs Database First",
    "Raw SQL / FromSqlRaw aur stored procedure call karna",
    "EF Core vs Dapper vs ADO.NET — trade-off",
    "Transaction handling, SaveChanges ka behaviour"
  ]},
  { g:"Patterns", items:[
    "Repository pattern — fayda aur criticism",
    "Unit of Work pattern",
    "Factory, Singleton, Strategy, Mediator/CQRS ka basic idea"
  ]}
]},

{ id:"angular", title:"Angular", note:"Flow poocha jata hai: main.ts se lekar view render tak. Change detection aur RxJS pe depth chahiye.", groups:[
  { g:"Angular flow aur basics", items:[
    "Bootstrap flow: main.ts → AppModule → AppComponent → template render",
    "Component, Module, Service ka role",
    "Component lifecycle hooks — order ke saath",
    "ngOnInit vs constructor — kaam kya alag hai",
    "ngOnChanges kab trigger hota hai",
    "ngOnDestroy mein kya cleanup karte ho",
    "Data binding ke 4 types: interpolation, property, event, two-way",
    "@Input / @Output / EventEmitter — parent-child communication",
    "ViewChild aur ContentChild",
    "Directives: structural (*ngIf, *ngFor) vs attribute (ngClass, ngStyle)",
    "Custom directive banana",
    "Pipes — pure vs impure, custom pipe",
    "Angular vs AngularJS, SPA kya hota hai",
    "NgModule ke parts: declarations, imports, providers, exports, bootstrap",
    "Feature module aur Shared module ka structure",
    "Decorators kya hain (@Component, @Injectable, @NgModule)",
    "ng-template vs ng-container vs ng-content",
    "ViewEncapsulation — Emulated, ShadowDom, None",
    "@HostListener aur @HostBinding",
    "Renderer2 kyun, direct DOM access kyun nahi",
    "Angular CLI commands jo roz use hote hain",
    "TypeScript kya hai — JS ka superset, compile kaise hota hai",
    "TS types, interface vs type, generics, enum",
    "Access modifiers TypeScript mein",
    "DOM kya hai, Angular DOM ko kaise update karta hai"
  ]},
  { g:"Change detection aur performance", items:[
    "Change detection kaise kaam karti hai (Zone.js)",
    "Default vs OnPush strategy",
    "trackBy *ngFor mein kyun",
    "async pipe ka fayda",
    "Lazy loading modules",
    "AOT vs JIT compilation",
    "Preloading strategy",
    "Bundle size kam karna, tree shaking",
    "ChangeDetectorRef — markForCheck vs detectChanges",
    "Angular Universal / SSR ka basic idea"
  ]},
  { g:"RxJS", items:[
    "Observable vs Promise — difference",
    "subscribe, unsubscribe, memory leak",
    "Subject vs BehaviorSubject vs ReplaySubject",
    "map, filter, tap",
    "switchMap vs mergeMap vs concatMap vs exhaustMap",
    "debounceTime aur distinctUntilChanged (search box use case)",
    "forkJoin vs combineLatest",
    "catchError aur retry",
    "takeUntil pattern se unsubscribe"
  ]},
  { g:"Services, forms, routing", items:[
    "Service aur DI — providedIn: 'root' ka matlab",
    "HttpClient — GET/POST, error handling",
    "HttpInterceptor — JWT token attach karna",
    "Template-driven vs Reactive forms",
    "FormGroup, FormControl, FormArray, custom validator",
    "Routing — routerLink, params, queryParams",
    "Route guards: CanActivate, CanDeactivate, Resolver",
    "State management basics (service + BehaviorSubject, ya NgRx)",
    "Standalone components aur Signals (naya Angular)",
    "InjectionToken kya hai aur kab chahiye",
    "Hierarchical injector — root vs component-level provider",
    "Router events aur navigation lifecycle",
    "Dynamic component load karna",
    "Jasmine + Karma se unit test — component aur service",
    "environment.ts se environment-based config"
  ]}
]},

{ id:"postgres", title:"PostgreSQL", note:"Practical round mein laptop pe query likhwate hain. Syntax fluency chahiye, theory ke saath.", groups:[
  { g:"SQL basics aur DDL", items:[
    "DDL, DML, DCL, TCL — kaunsa command kahan",
    "Primary key vs Unique key vs Foreign key",
    "Constraints: NOT NULL, CHECK, DEFAULT, UNIQUE",
    "DELETE vs TRUNCATE vs DROP",
    "SERIAL vs IDENTITY vs Sequence",
    "Common data types + JSONB kab use karein",
    "View vs Materialized view — refresh kab karna padta hai",
    "Temp table vs CTE vs subquery",
    "Schema kya hai, search_path",
    "Roles aur GRANT/REVOKE basics",
    "ALTER TABLE — column add/drop/type change ka impact",
    "SQL vs NoSQL — kab kya choose karein",
    "Normalization (1NF, 2NF, 3NF) vs Denormalization"
  ]},
  { g:"Query writing (machine round)", items:[
    "2nd / Nth highest salary nikalna",
    "Department-wise highest salary (window function ya correlated subquery)",
    "GROUP BY + HAVING — WHERE se difference",
    "INNER / LEFT / RIGHT / FULL / CROSS JOIN — output ka farak",
    "LEFT JOIN + IS NULL se missing records dhoondhna",
    "Self join — employee aur uska manager",
    "Duplicate rows find karna aur delete karna (ctid ya ROW_NUMBER)",
    "CTE (WITH clause) se readable query",
    "Recursive CTE — hierarchy / tree traversal",
    "Subquery vs JOIN — kab kya better",
    "EXISTS vs IN vs JOIN",
    "CASE WHEN se conditional aggregation",
    "COALESCE, NULLIF, NULL handling",
    "Date functions — date_trunc, age, interval, generate_series",
    "String functions — concat, split_part, LIKE vs ILIKE",
    "UNION vs UNION ALL",
    "INSERT ... ON CONFLICT (upsert)",
    "RETURNING clause",
    "LIMIT / OFFSET pagination aur uska performance problem",
    "Keyset pagination (WHERE id > last_id)",
    "Aggregate functions: COUNT, SUM, AVG, MIN, MAX — NULL ka behaviour",
    "COUNT(*) vs COUNT(column) vs COUNT(DISTINCT)",
    "array_agg aur string_agg",
    "JSONB query karna (->, ->>, @>)"
  ]},
  { g:"Window functions", items:[
    "ROW_NUMBER vs RANK vs DENSE_RANK",
    "PARTITION BY aur ORDER BY ka role",
    "LAG aur LEAD — previous/next row compare",
    "Running total (SUM OVER)",
    "FIRST_VALUE, LAST_VALUE, NTILE"
  ]},
  { g:"Indexing aur performance", items:[
    "Index internally kaise kaam karta hai (B-tree)",
    "B-tree vs GIN vs GiST vs BRIN — kab kaunsa",
    "Composite index — column ka order kyun matter karta hai",
    "Partial index aur covering index",
    "Index kab NAHI use hota (function on column, low selectivity, type mismatch)",
    "EXPLAIN vs EXPLAIN ANALYZE padhna",
    "Seq Scan vs Index Scan vs Bitmap Heap Scan",
    "Nested Loop vs Hash Join vs Merge Join",
    "Slow query ko debug karne ka step-by-step approach",
    "Clustered vs Non-clustered index — ek table mein clustered ek hi kyun",
    "Covering index kya hai",
    "SARGable query kya hoti hai — WHERE mein column pe function lagane se index kyun mar jata hai",
    "Blocking vs Deadlock ka difference",
    "SQL Server DMV (sys.dm_exec_query_stats) se slow query dhoondhna",
    "Composite primary key — kab zaroori hoti hai"
  ]},
  { g:"Transactions aur internals", items:[
    "ACID properties — har ek ka matlab",
    "Isolation levels: Read Committed, Repeatable Read, Serializable",
    "Dirty read, non-repeatable read, phantom read",
    "MVCC kaise kaam karta hai",
    "Locks aur deadlock — kaise hota hai, kaise avoid karein",
    "VACUUM, autovacuum aur table bloat",
    "Stored procedure vs function PostgreSQL mein",
    "Trigger — kab use karein aur kab nahi",
    "Normalization (1NF–3NF) vs Denormalization",
    "Partitioning — range vs list, partition pruning",
    "Connection pooling (PgBouncer) kyun zaroori hai",
    "Replication — streaming vs logical",
    "Refcursor return karna aur .NET se consume karna",
    "Exception handling stored procedure ke andar",
    "COMMIT / ROLLBACK / SAVEPOINT",
    "pg_stat_activity se running query dekhna aur kill karna",
    "pg_dump / pg_restore se backup aur restore",
    "Foreign Data Wrapper (FDW) kya hai",
    "Deadlock ka real example aur uska fix"
  ]}
]},

{ id:"resume", title:"Tumhare resume ke deep-dive topics", flagged:true, note:"Resume pe Kafka, Redis, Tile38, TCP likha hai — interviewer yahin sabse zyada drill karega. Har answer mein apne project ka concrete number ya decision hona chahiye.", groups:[
  { g:"Kafka", items:[
    "Producer, Broker, Consumer, Topic, Partition, Offset",
    "Consumer group aur rebalancing",
    "Partition key kaise choose ki — ordering guarantee kaise mili",
    "At-least-once vs at-most-once vs exactly-once",
    "Duplicate processing kaise handle kiya (idempotency)",
    "Consumer lag badhne pe kya karoge",
    "Retention aur log compaction",
    "Kafka vs RabbitMQ — kab kya"
  ]},
  { g:"Redis", items:[
    "Data structures: string, hash, list, set, sorted set",
    "Redis kyun, direct DB kyun nahi — apne case mein justify karo",
    "Cache-aside vs write-through vs write-behind",
    "TTL aur eviction policies (LRU, LFU)",
    "Cache invalidation strategy tumhare project mein kya thi",
    "Pub/Sub vs Streams",
    "Persistence: RDB vs AOF",
    "Redis kab galat choice hai"
  ]},
  { g:"TCP / GPS device panel", items:[
    "TCP stream-based hai — message boundary kaise define ki (framing)",
    "Partial packet aur packet coalescing handle karna",
    "Multiple firmware variants ka parsing — design kya rakha",
    "Thread safety — shared state kahan tha aur kaise protect kiya",
    "Connection drop aur reconnection handling",
    "Backpressure — device fast, processing slow ho to kya"
  ]},
  { g:"Tile38 aur geo", items:[
    "Geofencing concept — WITHIN, NEARBY, INTERSECTS",
    "Tile38 kyun, PostGIS kyun nahi",
    "Geo indexing kaise hoti hai",
    "Stop-arrival detection ka logic"
  ]},
  { g:"SignalR", items:[
    "SignalR kaise kaam karta hai (WebSocket, fallback transports)",
    "Multiple server instances pe scale — Redis backplane",
    "Hub, group, connection management",
    "DB trigger se app tak signal kaise pahuncha (NOTIFY/LISTEN)",
    "WebSocket vs SSE vs Long Polling"
  ]},
  { g:"Apna system explain karna", items:[
    "AVLS ka end-to-end data flow 3 minute mein whiteboard pe",
    "Scale ke numbers: kitne vehicles, kitne packets/sec, DB size",
    "Sabse bada bottleneck kya tha aur kaise solve kiya",
    "Agar 10x traffic aa jaye to kya todega",
    "Ek design decision jo galat tha aur ab kya alag karte"
  ]}
]},

{ id:"web", title:"Web aur networking fundamentals", note:"Service company screening rounds mein yeh sab rapid-fire aata hai.", groups:[
  { g:"HTTP aur web", items:[
    "HTTP request/response structure",
    "HTTP methods aur idempotency",
    "Status code families — 2xx, 3xx, 4xx, 5xx",
    "HTTP/1.1 vs HTTP/2",
    "Cookies, sessions, localStorage vs sessionStorage",
    "CORS aur preflight request",
    "URL type karne se page render tak kya hota hai"
  ]},
  { g:"Security", items:[
    "Hashing vs Encryption vs Encoding",
    "Salting kyun zaroori hai, bcrypt",
    "OAuth 2.0 aur OpenID Connect ka basic flow",
    "Keycloak / IDAM ka role",
    "SQL Injection, XSS, CSRF — aur unka bachav",
    "SSL/TLS handshake, HTTPS kaise secure hai",
    "Rate limiting aur DDoS protection",
    "Webhook vs Web service / API"
  ]}
]},

{ id:"devops", title:"DevOps aur infrastructure", note:"Yeh tumhara edge hai — zyadatar candidates yahan blank hote hain.", groups:[
  { g:"Git", items:[
    "clone, pull, fetch, add, commit, push — basic flow",
    "Branch banana, checkout, switch",
    "Merge vs Rebase — history pe kya farak",
    "Merge conflict resolve karna",
    "git stash, git reset vs git revert",
    "Cherry-pick kab use karte ho",
    "Pull Request flow aur acchi PR description",
    "Branching strategy (feature branch, develop, main)"
  ]},
  { g:"Agile, SDLC aur process", items:[
    "SDLC ke phases: Requirement → Planning → Design → Development → Testing → Deployment → Maintenance",
    "Waterfall vs Agile",
    "Scrum — sprint, sprint planning, daily standup, retrospective",
    "Scrum Master, Product Owner, team ka role",
    "Daily standup mein kya bolte ho (kal kya kiya, aaj kya, blocker)",
    "JIRA / ticket workflow",
    "Code review mein kya dekhte ho",
    "Onshore-offshore team ke saath communication",
    "Unit test vs Integration test vs System test"
  ]},
  { g:"Containers aur CI/CD", items:[
    "Docker image vs container",
    "Dockerfile, layers, multi-stage build",
    "docker-compose se multi-container setup",
    "Volume aur network basics",
    "Container vs VM",
    "CI/CD pipeline ke stages — Jenkins ya GitLab CI",
    "Build, test, deploy automation ka flow"
  ]},
  { g:"Linux aur server", items:[
    "Rozmarra commands: grep, awk, sed, find, ps, top, df, netstat/ss",
    "Log dekhna — tail -f, journalctl",
    "File permissions aur chmod/chown",
    "systemd service manage karna",
    "Nginx reverse proxy — config aur kyun chahiye",
    "curl se API test karna",
    "SSL certificate install aur renew",
    "Server slow hai — debug karne ka order"
  ]},
  { g:"Cloud aur monitoring", items:[
    "GCP Compute Engine instance kya hai, VPC aur firewall rules",
    "Load balancer ka kaam",
    "Horizontal vs Vertical scaling",
    "Kibana / ELK se log search",
    "Monitoring aur alerting ka basic setup",
    "Cloud computing kya hai, companies kyun use karti hain",
    "IaaS vs PaaS vs SaaS, Serverless kya hai",
    "Azure App Service, Azure Functions, Blob Storage, Azure SQL DB, Service Bus",
    "Azure DevOps — build pipeline vs release pipeline, artifacts",
    "AWS equivalents: EC2, S3, RDS, Lambda",
    "Cloud mein secrets rakhna — Azure Key Vault / AWS Secrets Manager",
    "Deployment flow: code push → build → test → artifact → QA → production"
  ]}
]},

{ id:"design", title:"System design (basic level)", note:"Tumse FAANG-level design nahi chahiye. Thinking chahiye. Apna AVLS system hi best answer hai.", groups:[
  { g:"Concepts", items:[
    "Monolith vs Microservices — trade-offs",
    "Load balancing aur health checks",
    "Caching layers kahan-kahan lagti hain",
    "Database replication aur sharding",
    "CAP theorem",
    "Event-driven architecture",
    "API Gateway ka role",
    "Circuit breaker aur retry with backoff",
    "Synchronous vs Asynchronous communication"
  ]},
  { g:"Design practice", items:[
    "Real-time vehicle tracking system (tumhara apna — sabse strong)",
    "Notification service",
    "URL shortener",
    "Rate limiter"
  ]}
]},

{ id:"coding", title:"Practical / machine round coding", note:"Ahmedabad mein aksar laptop deke bolte hain — likhna aana chahiye, sirf bolna nahi.", groups:[
  { g:"C# coding problems", items:[
    "String reverse — built-in ke bina",
    "Palindrome check",
    "Anagram check",
    "String mein first non-repeating character",
    "Array mein duplicates find karna",
    "Array mein second largest number",
    "FizzBuzz aur uske variants",
    "Factorial / Fibonacci — loop aur recursion dono",
    "Prime number check",
    "Two sum",
    "Sentence mein word frequency count (Dictionary)",
    "List of objects ko LINQ se group aur sort karna",
    "Employee list se department-wise max salary — LINQ mein",
    "String mein vowels/characters count",
    "Sentence mein words reverse karna",
    "Array rotate karna",
    "Missing number in array 1..n",
    "Two arrays ka common element",
    "Matrix / 2D array traversal",
    "Sorted array mein binary search",
    "Bubble sort ya selection sort hath se likhna",
    "Linked list reverse (agar DSA round hai)",
    "Sum of digits / Armstrong / perfect number type basics",
    "Reverse a number (digit by digit, while loop)",
    "Palindrome number check",
    "Swap two numbers — temp ke saath aur bina temp ke",
    "Largest number in array (foreach + max)"
  ]},
  { g:"Round ke doosre parts", items:[
    "Ek chhota CRUD Web API 30 minute mein bana lena",
    "Diya hua SQL slow hai — optimize karke dikhana",
    "Diya hua code review karna aur bugs batana",
    "Angular mein chhota component + service + HTTP call"
  ]}
]},

{ id:"hr", title:"HR aur behavioural", note:"Technical clear karke yahan reject hona sabse mehenga hai. Answers likh ke rakho.", groups:[
  { g:"Ready rakho", items:[
    "Apna introduction — 90 second, structured",
    "Company chhodne ka reason (blame-free version)",
    "Sabse challenging technical problem jo solve kiya",
    "Production issue jo tumne debug kiya — step by step",
    "Ek galti jo hui aur usse kya seekha",
    "Team conflict ya disagreement kaise handle kiya",
    "Strength aur weakness — honest aur specific",
    "Agle 3 saal ka plan",
    "Current aur expected CTC — number ready rakho",
    "Notice period aur joining date",
    "Interviewer se poochhne ke liye 3 sawaal"
  ]}
]}
];

const CHEAT = [
{g:"ASP.NET Core — pipeline", items:[
["app.Use","Middleware add karta hai, kaam karke next() call karke control aage pass karta hai."],
["app.Run","Terminal middleware — next() call nahi karta, pipeline wahin khatam."],
["app.Map","Request path ke hisaab se pipeline branch karta hai."],
["Custom middleware","Request logging / correlation ID trace karne ke liye, aur exception handling ke liye likha jata hai."],
["Global exception handling","Ek middleware jo consistent error shape (status code + message) return kare. Saath mein [ApiController] auto 400 deta hai bad request pe."],
["ASP.NET Core request pipeline","Har HTTP request middleware pipeline se guzarti hai, phir routing → controller → response."],
["MVC request lifecycle","Browser request → Routing URL check → Controller select → Action execute → Model/data process → ViewResult/JsonResult → Response browser ko."],
["Filters (MVC)","Action execute hone se pehle/baad chalte hain. Types: Authorization, Action, Result, Exception."],
["Action result types","ViewResult, RedirectResult, JsonResult, FileResult."],
["Common status codes","200 OK, 201 Created, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404 Not Found, 500 Internal Server Error."],
["Web API","HTTP services banane ke liye jo data (mostly JSON) return karti hain — Angular, React, mobile app consume karte hain."],
["Swagger","API documentation aur API testing ke liye."],
["Web API optimize karna","async/await, caching, pagination, sahi status code, DTOs, DB index, DB calls kam karna."],
["Large result handling","Pagination — page=2 & pageSize=50 bhejo, page ke saath total count return karo."],
["Third-party API call","HttpClient ko DI se inject karke. Token ya API key se authentication, JSON response parse, error handling."],
["Background hosted service","Long-running ya scheduled kaam request ke bahar chalane ke liye."],
["Caching","Frequently-read, rarely-changing data memory mein rakho taaki har baar DB hit na ho."],
["CORS","Cross-Origin Resource Sharing — ek domain ke frontend ko doosre domain ki API call karne deta hai."],
["Serialization / Deserialization","Object → JSON serialization; JSON → object deserialization."],
["ViewData","Dictionary, string key — controller se view tak data."],
["ViewBag","ViewData ke upar dynamic wrapper."],
["TempData","Do request ke beech data rakhta hai — redirect ke baad kaam aata hai."],
["HTML Helper","Server side se HTML control generate karta hai — Html.TextBoxFor(), Html.LabelFor()."],
["DTO","Data Transfer Object — frontend aur backend ke beech sirf zaroori data transfer karta hai."],
["Loose coupling","Interface aur DI se classes ke beech dependency kam karna — code maintainable aur testable banta hai."],
["Folder structure","Controller → Service → Repository → Model/DTO. Helpers aur interfaces alag."],
["Version matrix","Framework 4.8 / MVC 5 / VS 2022 / SQL 2022 / SSMS 20 · .NET 8, 6, Core 3.1 · Angular 15+, React 18, Node 20."]
]},
{g:"C# — core", items:[
["Class","Blueprint, logical entity — memory allocate nahi hoti. Jaise Booking ek class."],
["Object","Class ka instance, physical entity — ek customer ki booking ek object."],
["Interface","Sirf contract define karta hai. Ek class multiple interface implement kar sakti hai."],
["Abstract class","Abstract aur implemented dono method rakh sakti hai. Par class sirf ek abstract class inherit kar sakti hai."],
["Abstract class kab","Jab common base functionality dena ho — jaise saare payment types ka common logic PaymentBase mein."],
["Interface kab","Jab sirf behaviour define karna ho — Pay(), Refund() — jo multiple class implement karein."],
["Access modifiers","public = sab jagah, private = sirf class ke andar, protected = class + subclass, internal = same assembly."],
["Constructor","Special method jo object banate hi automatically chalta hai."],
["try / catch / finally","try mein risky code, catch mein specific exception, finally hamesha chalta hai — cleanup ke liye."],
["Synchronous","Task poora hone tak wait karta hai."],
["Asynchronous","Execution block nahi karta, doosre operations chalte rehte hain."],
["Dependency Injection","Design pattern — required object bahar se provide hote hain, manually new nahi karte. Loose coupling, testing, maintainability."],
["CLR","Common Language Runtime — .NET ka runtime environment. Code execution, security, exception handling manage karta hai."],
["CTS","Common Type System — saari .NET languages ke liye common types."],
["CLS","Common Language Specification — rules jo saari .NET languages follow karti hain taaki saath kaam kar sakein."],
["Repository pattern","Data access logic ko business logic se alag karta hai — code clean, testable, maintainable."],
["First() vs FirstOrDefault()","First() record na mile to throw karta hai; FirstOrDefault() default (null/0) return karta hai."],
["Single() vs SingleOrDefault()","Single() bilkul ek record expect karta hai; SingleOrDefault() zero allow karta hai par ek se zyada pe throw."],
["LINQ — highest salary","employees.Select(x => x.Salary).Distinct().OrderByDescending(x => x).Skip(1).FirstOrDefault()"],
["REST API design","Controller banao, GET/POST/PUT/DELETE verbs se action define karo. API clean, secure aur properly validated honi chahiye."]
]},
{g:"SQL aur performance", items:[
["SQL Index","Query search performance improve karta hai — book ke index jaisa kaam."],
["Clustered index","Table mein data ka physical order decide karta hai. Ek table mein sirf ek."],
["Non-clustered index","Alag structure jo data ka pointer rakhta hai. Ek table mein multiple ho sakte hain."],
["Covering index","Non-clustered index jisme query ke saare zaroori columns include hote hain — table pe jaana hi nahi padta."],
["SARGable query","Aisi query jispe engine index use kar sake. WHERE OrderDate >= '2026-09-06' SARGable hai; column pe function lagao to nahi."],
["Blocking","Ek transaction ne lock liya hai, doosre ko wahi lock chahiye — doosra bas wait karta hai. Normal aur temporary."],
["Deadlock","Do transaction ek doosre ka wait kar rahe hain — koi aage nahi badh sakta."],
["DMV","Dynamic Management Views — SQL Server performance monitor karne ke liye. sys.dm_exec_query_stats se slow queries milti hain."],
["N+1 problem","Ek query se N records laaye, phir har record ke liye ek aur query. 100 orders ke liye customer alag-alag fetch = 101 queries."],
["SQL Injection","Attack jisme user input seedha SQL query mein add ho jata hai. Bachav: parameterized queries ya EF."],
["WHERE clause","Records filter karta hai — SELECT, UPDATE, DELETE sab mein."],
["SELECT statement clauses","WHERE, ORDER BY, HAVING, JOIN, TOP, LIKE, IN, BETWEEN."],
["Composite primary key","Ek se zyada column milke row uniquely identify karte hain. Jaise student(StudentID, CourseID) — akele koi unique nahi."],
["Entity Framework","ORM tool — har operation ke liye raw SQL likhne ki jagah C# objects se DB ke saath kaam karo."],
["Dapper","Lightweight ORM, better performance — par SQL query khud likhni padti hai."]
]},
{g:"Angular", items:[
["Angular","TypeScript-based frontend framework, Google ka — SPA banane ke liye. Two-way binding, routing, services."],
["Main features","Component-based architecture — HTML template + TS class + CSS style."],
["Component","Angular app ka basic building block."],
["Module","Related components, directives aur services ko group karta hai."],
["Data binding","Component aur template ko connect karta hai. Types: interpolation {{ }}, property binding [ ], event binding ( ), two-way [(ngModel)]."],
["One-way vs Two-way","One-way = data ek direction mein, debug aasan. Two-way = dono taraf, zyada interactive."],
["Directive","DOM element ka behaviour ya appearance badalta hai. Types: Component, Structural, Attribute."],
["ngIf / ngFor","ngIf element hide/show karta hai; ngFor data loop karta hai."],
["Dependency Injection","Design pattern jisse services components ko provide hoti hain."],
["Routing","Alag-alag components/pages ke beech navigation. const routes: Routes = [{ path: 'home', component: HomeComponent }]"],
["Pipe","Template mein data display ke liye transform karta hai — date, currency."],
["Custom pipe","Business requirement ke hisaab se apna pipe bana sakte ho — custom data transformation."],
["Observable","Stream jo time ke saath multiple values emit karta hai. Lazy aur cancellable, RxJS based."],
["Promise","Ek hi baar single value ke saath resolve hota hai, cancellable nahi. Native JS, immediate execution."],
["Component communication","Parent → Child: @Input. Child → Parent: @Output + EventEmitter."],
["Interceptor","HTTP calls ke liye middleware — auth token add karna, logging, error handle karna."],
["AOT","Ahead-of-Time compilation — templates build time pe compile hote hain. Faster load, smaller bundles."],
["Angular lifecycle","Hooks fixed order mein chalte hain jab component create, update aur destroy hota hai. Common: ngOnInit, ngOnChanges, ngOnDestroy."],
["ngOnInit","Component initialize hone ke baad ek baar chalta hai. API calls aur data loading ke liye."],
["ngOnDestroy","Component memory se hatne se just pehle. Observables unsubscribe, timers clear."],
["RxJS","Reactive programming aur observables ke saath kaam karne ki library."],
["ViewChild","Parent component se child component, directive ya DOM element ko directly access karne ke liye."],
["SPA","Single Page Application — ek HTML page load hota hai aur content dynamically update hota hai, poora page reload nahi."],
["TypeScript","JavaScript ka superset, Microsoft ka."],
["DOM","Document Object Model — HTML ka structure object ke roop mein, jise JS aur Angular dynamically update karte hain."],
["Template","Component se associated HTML view — data kaise dikhega aur user kaise interact karega."],
["Event binding","Angular ko user action pe respond karne deta hai — button click, keyboard, mouse event."],
["Interpolation","{{ }} se component ka data HTML template mein display karna."],
["Decorator","Special function jo class, method ya property ko metadata deta hai — @Component, @Injectable."],
["Property binding","[ ] se component ki value HTML element ki property mein bind karna."]
]},
{g:"Cloud, DevOps, Agile", items:[
["Cloud computing","Physical server manage karne ki jagah internet pe computing resources use karna — server, storage, DB."],
["Cloud kyun use karte hain","Scalability (traffic ke hisaab se resources badhao-ghatao), cost saving (jitna use utna pay), faster deployment."],
["Azure Functions","Serverless compute — sirf code likho, server aur scaling automatic. Jaise order purchase pe invoice generate + email."],
["Azure App Service","Web app aur API host karne ka platform."],
["Azure Storage / Blob","Cloud storage — file, image, document rakhne ke liye."],
["Azure SQL DB","Microsoft ki cloud-based relational database service."],
["Azure Service Bus","Messaging service — apps ke beech asynchronous communication."],
["AWS equivalents","EC2 = virtual machine, S3 bucket = object/file storage."],
["API Gateway","Saari microservices ke liye single entry point."],
["Docker","Containerization platform — app ko uski saari dependencies ke saath package karta hai taaki har environment mein consistently chale."],
["Container","Lightweight package jisme app code aur libraries hoti hain."],
["Container vs VM","VM mein poora OS hota hai — heavy, slow startup. Container light aur fast."],
["DevOps","Culture jo development aur operations ko jodta hai — automated delivery aur better collaboration."],
["Azure DevOps","Platform jo source control, CI/CD pipelines aur work item tracking deta hai."],
["Build pipeline","Code automatically compile karta hai, tests chalata hai, build artifacts banata hai."],
["Release pipeline","Application ko alag environments mein deploy karta hai — Dev, QA, Production."],
["Deployment flow","Developer code Git pe push karta hai → build pipeline compile karti hai → unit tests → artifacts → release pipeline QA pe deploy → phir production."],
["Version control","System jo source code ke changes track karta hai aur multiple developers ko collaborate karne deta hai."],
["Git commands","clone, pull, checkout, branch, add, commit, push, merge."],
["Merge","Ek branch ke changes doosri mein laata hai aur history linear nahi rakhta — merge commit banta hai."],
["Rebase","Commits ko doosri branch ke upar move karta hai — history linear rehti hai."],
["Logging","Application events, errors aur monitoring info record karna — debugging ke liye."],
["Connection string management","Hardcode kabhi nahi. appsettings, environment variables, Azure Key Vault ya AWS Secrets Manager mein rakho — alag env ke liye alag."],
["Environment variable","App code ke bahar stored configuration value."],
["SDLC","Requirement Gathering → Planning → Design → Development → Testing → Deployment → Maintenance."],
["Agile","Development methodology jisme kaam chhote sprints mein hota hai, continuous feedback aur improvement ke saath."],
["Scrum","Agile ke andar framework — roles: Scrum Master, Product Owner, Team. Sprint planning, daily standup, development, testing, demo."],
["Daily standup","Kal kya kiya, aaj kya kar raha hoon, blocker kya hai."],
["Onshore / offshore","Clear communication, decisions document karna, detailed PR description."],
["Unit test","Ek chhota piece isolation mein test karna."],
["Integration test","Kai pieces saath mein kaam kar rahe hain ya nahi."],
["System test","Poori app end-to-end — aksar QA ka kaam."],
["Monolith","Ek deployable app — start karna simple, scale karna mushkil."],
["Microservices","Chhoti independent services jo alag-alag scale aur deploy hoti hain — complexity ki keemat pe. Jaise user, product, order, payment alag."]
]},
{g:"Coding — ratne wale snippets", items:[
["Fibonacci","int a=0, b=1; loop mein: temp = a+b; a = b; b = temp;"],
["Prime number","i = 2 se n tak loop; agar n % i == 0 to prime = false; break."],
["Largest number","max = arr[0]; foreach: agar n > max to max = n."],
["Second largest","first aur second ko int.MinValue se start karo; n > first ho to second = first, first = n; warna n > second && n != first ho to second = n."],
["Remove duplicates","HashSet<int> mein daalo — duplicate apne aap hat jaate hain."],
["Reverse string","input.ToCharArray() → Array.Reverse(chars) → new string(chars)"],
["Reverse number","while(num > 0): digit = num % 10; rev = rev * 10 + digit; num = num / 10;"],
["Palindrome number","Number reverse karo aur original se compare karo."],
["Swap two numbers","temp = a; a = b; b = temp;"],
["FizzBuzz","i % 3 == 0 && i % 5 == 0 → FizzBuzz; i % 3 == 0 → Fizz; i % 5 == 0 → Buzz; warna i."]
]},
{g:"Asli poochhe gaye — C# / .NET", items:[
["Components of .NET","CLR (runtime), CTS (common types), CLS (common rules), BCL/FCL (built-in class libraries), aur languages (C#, VB, F#)."],
["FCL vs BCL","BCL = core basic classes (System namespace). FCL = poori framework library, BCL usme shamil hai."],
["Type safety","Compiler ensure karta hai ki variable apne declared type ka hi data rakhe — galat type assign karoge to compile error."],
["Stack vs Heap","Value types stack pe, reference types heap pe. GC sirf heap manage karti hai kyunki stack apne aap scope khatam hote hi clear ho jata hai."],
["GC kaise kaam karti hai","Generations mein: Gen 0 (naye objects), Gen 1, Gen 2 (lambe chalne wale). Jo objects reachable nahi hain unki memory free ho jati hai."],
["Sealed class","Aisi class jise inherit nahi kiya ja sakta. sealed keyword."],
["Partial class","Ek hi class ka code multiple files mein baant sakte ho — compile hote waqt sab mil jata hai. Designer-generated code mein use hota hai."],
["Types of classes","Static, Abstract, Sealed, Partial, Generic, Nested."],
["Constructor inheritance mein","Base class ka constructor pehle chalta hai, phir derived class ka. base(...) se parameters pass karte ho."],
["Multiple inheritance C# mein","Classes ke liye allowed nahi (diamond problem). Multiple interfaces implement karke achieve karte ho."],
["A, B, C, D ki property Z mein bina inheritance/interface","Composition use karo — Z ke andar A, B, C, D ke objects ko property bana ke rakho. has-a relationship, is-a nahi."],
["readonly vs static","readonly = value declaration ya constructor mein set hoti hai, phir change nahi. static = class-level, saare instances mein shared, aur baad mein bhi change ho sakti hai."],
["const vs readonly","const compile-time pe fix, implicitly static. readonly runtime pe constructor mein set ho sakti hai — har object ki alag value."],
["Pass by value vs reference","Default value pass hoti hai (copy). ref / out keyword se reference pass hota hai — original variable change hota hai."],
["Dispose vs Finalize","Dispose developer khud call karta hai (IDisposable, using block) — deterministic. Finalize GC call karti hai, kab chalega pata nahi."],
["Types of exceptions","System exceptions (NullReference, DivideByZero, IndexOutOfRange) aur Application/custom exceptions."],
["Finally catch ke baad chalta hai?","Haan — exception aaye ya na aaye, finally hamesha chalta hai. Cleanup ke liye."],
["IList vs IEnumerable","IEnumerable sirf iterate karne deta hai, forward-only. IList index se access, add, remove sab deta hai."],
["Lambda expression","Short anonymous function. x => x.Salary > 50000 — LINQ mein sabse zyada use hota hai."],
["Authentication vs Authorization","Authentication = tum kaun ho (login). Authorization = tum kya kar sakte ho (permission)."],
[".NET Core mein authentication","JWT bearer token, cookie authentication, ya Identity. Program.cs mein AddAuthentication + AddJwtBearer, phir UseAuthentication se pehle UseAuthorization."],
["API key authentication ke tareeke","Custom middleware, custom AuthenticationHandler, ya action filter — header se key padho aur validate karo."],
["Program.cs vs Startup.cs","Purane version mein Startup.cs alag tha (ConfigureServices + Configure). .NET 6+ mein sab Program.cs mein minimal hosting model se aa gaya."],
["MVC action methods","ViewResult, PartialViewResult, JsonResult, RedirectResult, RedirectToActionResult, FileResult, ContentResult, StatusCodeResult."],
["Action Filter","Action execute hone se pehle aur baad mein code chalata hai — logging, validation, timing ke liye. OnActionExecuting / OnActionExecuted."],
["Attribute routing","Controller ya action ke upar route directly likhna — [Route(api/orders/{id})]. Conventional routing se zyada control deta hai."],
["Ek view se doosre view pe redirect","return RedirectToAction(ActionName, ControllerName); ya return View(OtherView)."],
["TempData view mein use ho sakta hai?","Haan. TempData internally Session use karta hai, isliye redirect ke baad bhi value milti hai — par ek baar read hone ke baad hat jati hai (Keep/Peek se rok sakte ho)."],
["State management","Client side: Hidden field, Cookie, Query string, ViewState. Server side: Session, TempData, Cache, Application state."],
["Web API vs Web Service","Web Service (SOAP) XML based, heavy, WSDL chahiye. Web API REST based, JSON, lightweight, kisi bhi HTTP client se chalti hai."],
["URL vs URN","URL batata hai resource kahan hai (location) — https://site.com/a. URN batata hai resource ka naam kya hai (identity), location nahi."],
["200 status code se success message","Haan — 200 OK ke saath response body mein message bhej sakte ho. Naya resource bana ho to 201 Created zyada sahi hai."],
["SOLID","S: ek class ka ek kaam. O: extension ke liye open, modification ke liye closed. L: child class parent ki jagah chal sake. I: bade interface ki jagah chhote. D: concrete class pe nahi, abstraction pe depend karo."],
["Software architecture","App ka overall structure — layers (Presentation, Business, Data Access), unke beech communication, aur patterns (Monolith, Microservices, Layered, MVC)."]
]},
{g:"Asli poochhe gaye — SQL", items:[
["varchar vs nvarchar","varchar non-Unicode, 1 byte per character. nvarchar Unicode, 2 bytes per character — multi-language data ke liye."],
["varchar2","Oracle ka data type hai, SQL Server mein nahi hota."],
["# vs ## temp table","#temp local temporary — sirf usi session mein dikhta hai. ##temp global temporary — saare sessions ko dikhta hai, last session close hone pe drop hota hai."],
["Primary key vs Composite primary key","Primary key ek column se row uniquely identify karti hai. Composite key do ya zyada columns milke — jaise (StudentID, CourseID)."],
["6th highest salary","SELECT DISTINCT Salary FROM Salary ORDER BY Salary DESC OFFSET 5 ROWS FETCH NEXT 1 ROWS ONLY; ya DENSE_RANK() ke saath."],
["OFFSET","Pehle kitni rows skip karni hain. OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY — pagination ke liye."],
["10 dependent inserts, 9th pe error","Poore block ko transaction mein daalo: BEGIN TRANSACTION + BEGIN TRY ... COMMIT ... END TRY BEGIN CATCH ROLLBACK TRANSACTION; THROW; END CATCH. Ya to sab insert honge ya kuch bhi nahi."],
["SQL mein exception handling","BEGIN TRY ... END TRY BEGIN CATCH ... END CATCH. ERROR_MESSAGE(), ERROR_NUMBER() se detail, THROW se dobara raise."],
["Transaction, Commit, Rollback","Transaction = statements ka group jo ek unit ki tarah chalta hai. COMMIT = permanent save. ROLLBACK = sab undo."],
["ACID","Atomicity (sab ya kuch nahi), Consistency (DB valid state mein rahe), Isolation (transactions ek doosre ko disturb na karein), Durability (commit ke baad data safe)."],
["Normalization","Data ko organize karke redundancy hatana. 1NF: atomic values. 2NF: partial dependency hatao. 3NF: transitive dependency hatao."],
["Types of joins","INNER (dono mein match), LEFT (left ki sab + match), RIGHT, FULL OUTER (dono ki sab), CROSS (cartesian product), SELF (khud se join)."],
["Cross join","Dono tables ka cartesian product — har row har row ke saath. 10 x 10 = 100 rows."],
["UPDATE mein join","UPDATE a SET a.Status = X FROM Orders a INNER JOIN Customers c ON a.CustId = c.Id WHERE ..."],
["DELETE mein join","DELETE a FROM Orders a INNER JOIN Customers c ON a.CustId = c.Id WHERE c.Active = 0"],
["UNION vs UNION ALL","UNION duplicates hata deta hai (isliye slow). UNION ALL sab rows rakhta hai, faster. Dono mein columns ka count aur type same hona chahiye."],
["INTERSECT","Dono queries mein jo rows common hain sirf wahi return karta hai."],
["HAVING vs WHERE","WHERE grouping se pehle rows filter karta hai. HAVING GROUP BY ke baad groups filter karta hai — aggregate condition HAVING mein hi lagti hai."],
["Aggregate functions","COUNT, SUM, AVG, MIN, MAX. NULL values ko ignore karte hain (COUNT(*) ke alawa)."],
["Cursor","Row-by-row processing ke liye. Set-based operation se bahut slow hai, isliye tabhi use karo jab koi aur raasta na ho."],
["Trigger","Automatic code jo INSERT / UPDATE / DELETE pe chalta hai. Audit log ya validation ke liye."],
["Stored procedure","Pre-compiled SQL block jo DB mein save rehta hai. Reusable, faster (execution plan cached), SQL injection se safe."],
["View","Virtual table — ek saved query. Complexity chhupata hai aur security deta hai. Materialized/indexed view actual data store karta hai."],
["Scalar-valued function","Ek single value return karti hai. SELECT dbo.GetAge(@dob)"],
["Table-valued function","Poora table return karti hai, usko FROM clause mein use kar sakte ho."],
["Function vs Stored procedure","Function value return karti hai aur SELECT mein use ho sakti hai, DML nahi kar sakti. SP DML kar sakta hai, transaction handle kar sakta hai, par SELECT ke andar nahi chalta."],
["MERGE","Ek hi statement mein INSERT + UPDATE + DELETE — source aur target compare karke. Upsert ke liye."],
["Indexing ka purpose","Query search fast karna. Poora table scan karne ki jagah index se seedha row tak pahunchna. Trade-off: INSERT/UPDATE thoda slow, extra storage."],
["Types of index","Clustered (data ka physical order, ek hi), Non-clustered (pointer rakhta hai, multiple), Unique, Composite, Filtered/Partial, Covering."],
["OLTP vs OLAP","OLTP = day-to-day transactions, bahut saari chhoti read/write, normalized. OLAP = analysis aur reporting, bade aggregate queries, denormalized (data warehouse)."],
["NULL handle karna SELECT mein","ISNULL(col, 0) ya COALESCE(col1, col2, 0). Comparison IS NULL / IS NOT NULL se hoti hai, = NULL se nahi."],
["Dapper","Lightweight micro-ORM. SQL khud likhna padta hai par EF se kaafi fast — reporting aur dashboard queries ke liye achha."]
]},
{g:"Asli poochhe gaye — Angular / JS / jQuery", items:[
["@Component decorator","Class ko Angular component banata hai. Metadata deta hai: selector, templateUrl, styleUrls."],
["Constructor vs ngOnInit","Constructor class banate hi chalta hai — sirf DI ke liye use karo. ngOnInit tab chalta hai jab Angular ne inputs set kar diye — API call aur initialization yahan."],
["main.ts / app.module","main.ts app ka entry point hai — platformBrowserDynamic().bootstrapModule(AppModule). AppModule root module hai aur AppComponent bootstrap hota hai."],
["ng serve pe kaunsi class start hoti hai","main.ts se AppModule bootstrap hota hai, aur AppModule ki bootstrap array mein AppComponent hoti hai — wahi pehle render hoti hai."],
["Angular code browser kaise samajhta hai","Browser TypeScript nahi samajhta. Angular compiler (AOT/Ivy) TS aur templates ko JavaScript mein compile karta hai, webpack bundle banata hai, browser wahi JS chalata hai."],
["Filter Angular mein","Angular (2+) mein AngularJS wala filter pipe nahi hai. Array pe JavaScript ka .filter() use karo ya custom pipe banao."],
["Service Angular mein","@Injectable class jisme shared business logic aur API calls hoti hain. DI se components mein inject hoti hai, aur singleton hoti hai."],
["ng-app","AngularJS (purana Angular 1.x) ka directive jo app ka root element mark karta tha. Naye Angular mein nahi hai."],
["Directives (AngularJS)","ng-app, ng-model, ng-repeat, ng-if, ng-show/ng-hide, ng-click."],
["var vs let","var function-scoped hai aur hoist hoke undefined ho jata hai. let block-scoped hai aur declare hone se pehle use karo to error (temporal dead zone)."],
["JS mein variable define karne se pehle use","var ke saath chalega par value undefined milegi (hoisting). let/const ke saath ReferenceError aayega."],
["null vs undefined","undefined = variable declare hua par value assign nahi hui. null = developer ne jaan-boojh ke khaali value set ki."],
["== vs ===","== type conversion karke compare karta hai (0 == false true hai). === type aur value dono check karta hai — hamesha yahi use karo."],
["filter() vs find()","filter() saare matching elements ka array deta hai. find() sirf pehla matching element deta hai, na mile to undefined."],
["setTimeout vs setInterval","setTimeout ek baar, given delay ke baad. setInterval baar-baar, har interval pe — clearInterval se rokna padta hai."],
["atob() / btoa()","JavaScript ke functions hain (jQuery ke nahi). btoa() = string se Base64 encode, atob() = Base64 se decode."],
["jQuery kya hai","JavaScript library hai (JSON library nahi) — DOM manipulation, event handling aur AJAX aasan banati hai."],
["jQuery events","click, dblclick, change, submit, keyup, hover, focus, blur. $(#btn).click(function(){ ... })"],
["JavaScript vs TypeScript","TypeScript JS ka superset hai — static types, interfaces, generics, compile-time error checking. Browser mein chalne se pehle JS mein compile hota hai."]
]},
{g:"Apne project ke baare mein (khud tayyar karo)", items:[
["Current project ki architecture","Layers, modules, services, DB, message queue — 3 minute mein whiteboard pe bolne layak ready rakho."],
["Current project ka domain","Kis industry ka problem solve karta hai, end users kaun hain, business value kya hai — ek line mein."],
["Current project ka framework aur version","Kaunsa .NET version, Angular version, DB version — exact number bolna aana chahiye."],
["Technical challenge","Ek asli problem: kya toota tha, tumne kaise debug kiya, kya fix kiya, result kya nikla. Numbers ke saath."],
["Team aur process","Team size, sprint length, code review kaise hota hai, deployment kaun karta hai."]
]}
];
