const DATA = [
{ id:"csharp", title:"C# aur OOPs", note:"Har interview yahin se shuru hota hai. Definition nahi — apne code ka example ready rakho.", groups:[
  { g:".NET platform basics", items:[
    ".NET Framework vs .NET Core vs .NET 5/6/8 — difference",
    "CLR kya hai, managed vs unmanaged code",
    "IL (Intermediate Language) aur JIT compilation",
    "CTS aur CLS ka matlab",
    "Assembly, DLL vs EXE, GAC",
    "Namespace vs Assembly",
    "Just-in-time vs Ahead-of-time compilation",
    ".NET Standard kya tha aur ab kyun relevant nahi"
  ]},
  { g:"OOPs pillars", items:[
    "Abstraction, Encapsulation, Inheritance, Polymorphism — har ek ka real example",
    "Abstract class vs Interface — kab kaunsa, aur kyun",
    "Method Overloading vs Overriding (compile-time vs runtime binding)",
    "virtual / override / new keyword ka farak",
    "Sealed class, static class, partial class",
    "Multiple inheritance C# mein kyun nahi — interface se kaise solve hota hai",
    "SOLID — paanchon principle, ek-ek line ka apna example"
  ]},
  { g:"Language fundamentals", items:[
    "Value type vs Reference type, Stack vs Heap",
    "Boxing aur Unboxing — performance impact",
    "const vs readonly vs static readonly",
    "string immutable kyun hai, StringBuilder kab use karein",
    "== vs .Equals() vs ReferenceEquals",
    "Access modifiers: public, private, protected, internal, protected internal",
    "Nullable types, null-coalescing (??), null-conditional (?.)",
    "var vs dynamic vs object",
    "ref vs out vs in parameters",
    "Struct vs Class — kab struct use karein",
    "Static constructor kab chalta hai",
    "Enum aur uska underlying type",
    "Indexer kya hota hai",
    "Extension method — kaise banate hain, restriction kya hai",
    "Anonymous type, Tuple, ValueTuple",
    "Record type (C# 9+) — class se kaise alag",
    "Shallow copy vs Deep copy",
    "Operator overloading",
    "Reflection kya hai, kahan use hoti hai",
    "Attributes — built-in aur custom",
    "Pattern matching, switch expression",
    "String interpolation vs concatenation vs String.Format",
    "Covariance aur Contravariance (basic idea)"
  ]},
  { g:"Collections aur Generics", items:[
    "Array vs List vs Dictionary vs HashSet — kab kya",
    "Dictionary lookup O(1) kaise — internally hashing",
    "IEnumerable vs ICollection vs IList",
    "Generics kyun — type safety aur boxing se bachav",
    "Delegate, Func, Action, Predicate",
    "Events aur delegate ka relation",
    "Lambda expression aur closure",
    "Multicast delegate",
    "Array vs ArrayList vs List — generic kyun better",
    "Stack vs Queue — LIFO/FIFO use cases",
    "IEnumerable vs IEnumerator — internally foreach kaise chalta hai",
    "yield return aur lazy iterator",
    "SortedList, SortedDictionary, ConcurrentDictionary",
    "Time complexity: List.Contains vs HashSet.Contains"
  ]},
  { g:"Memory aur exceptions", items:[
    "Garbage Collection — Gen 0, 1, 2 kaise kaam karti hain",
    "IDisposable, using block, Dispose vs Finalize",
    "Memory leak C# mein kaise hota hai (event handlers, static refs)",
    "try-catch-finally, custom exception class",
    "throw vs throw ex — stack trace ka farak"
  ]},
  { g:"Async aur threading", items:[
    "async/await internally kya karta hai (state machine, thread release)",
    "Task vs Thread vs ThreadPool",
    ".Result / .Wait() se deadlock kyun hota hai",
    "async void kyun avoid karna chahiye",
    "Task.Run kab use karein aur kab nahi",
    "CancellationToken ka use",
    "lock, Monitor, thread-safe collections",
    "Task.WhenAll vs Task.WhenAny",
    "Parallel.For / Parallel.ForEach aur PLINQ",
    "Race condition aur deadlock ka difference",
    "IAsyncEnumerable aur await foreach",
    "Synchronous code ko async mein convert karne ke rules"
  ]}
]},

{ id:"aspnet", title:"ASP.NET Core", note:"Request flow poora bolna aana chahiye — Kestrel se DB tak aur wapas.", groups:[
  { g:"Request pipeline", items:[
    "Poora flow: Kestrel → Middleware → Routing → Model Binding → Filters → Controller → Service → DB → Response",
    "Middleware kya hai, custom middleware kaise likhte ho",
    "app.Use vs app.Run vs app.Map",
    "Middleware ka order kyun matter karta hai (Authentication vs Authorization)",
    "Filters ke types: Authorization, Resource, Action, Exception, Result",
    "Middleware vs Filter — difference",
    "Program.cs / Startup.cs — ConfigureServices vs Configure",
    "Kestrel kya hai, IIS ke saath reverse proxy setup",
    "In-process vs Out-of-process hosting",
    "wwwroot aur static files middleware",
    "Minimal API vs Controller-based API"
  ]},
  { g:"MVC aur Web API essentials", items:[
    "MVC vs Web API — difference aur kab kya",
    "Controller, Action, IActionResult ke types (Ok, NotFound, BadRequest)",
    "Attribute routing vs Conventional routing",
    "Model Binding kaise kaam karti hai ([FromBody], [FromQuery], [FromRoute])",
    "ViewBag vs ViewData vs TempData vs Session (MVC)",
    "Partial View aur Razor basics",
    "Swagger / OpenAPI setup aur uska fayda",
    "File upload API kaise banate ho",
    "Async controller action ka fayda",
    "MVC request lifecycle: Browser → Routing → Controller → Action → Model → View/JsonResult → Response",
    "HTML Helpers (Html.TextBoxFor, Html.LabelFor)",
    "Version awareness: .NET Framework 4.8, Core 3.1, .NET 6/8, MVC 5, VS 2022 — tum kaunse pe ho aur kyun"
  ]},
  { g:"Caching, background work, testing", items:[
    "IMemoryCache vs IDistributedCache (Redis)",
    "Response caching aur cache headers",
    "IHostedService / BackgroundService se background job",
    "Health checks endpoint",
    "Unit testing — xUnit / NUnit basics",
    "Moq se dependency mock karna",
    "Unit test vs Integration test",
    "Testable code kaise likhte hain (DI ka role)"
  ]},
  { g:"Dependency Injection", items:[
    "DI kya hai aur kyun — loose coupling, testability",
    "Singleton vs Scoped vs Transient (yeh pakka poochha jayega)",
    "Captive dependency — Singleton mein Scoped inject karne pe kya hota hai",
    "Constructor injection vs property injection",
    "IServiceCollection mein service register karna",
    "Built-in DI container vs Autofac / third-party"
  ]},
  { g:"API design", items:[
    "REST principles, resource naming",
    "HTTP verbs: GET, POST, PUT, PATCH, DELETE — idempotency",
    "Status codes: 200, 201, 204, 400, 401, 403, 404, 409, 500",
    "PUT vs PATCH ka farak",
    "API versioning ke tareeke",
    "Model validation, DataAnnotations, ModelState",
    "DTO kyun use karte hain, entity direct return kyun nahi",
    "Global exception handling middleware",
    "CORS kya hai aur kyun chahiye",
    "Pagination, filtering, sorting API mein kaise dete ho",
    "Content negotiation aur JSON serialization settings",
    "AutoMapper ya manual mapping — trade-off",
    "Rate limiting API pe kaise lagate ho",
    "HttpClient vs IHttpClientFactory — socket exhaustion problem",
    "Third-party API call — token / API key handling, retry, timeout",
    "Serialization aur Deserialization — JSON to object aur wapas",
    "System.Text.Json vs Newtonsoft.Json",
    "Connection string aur secrets kahan rakhte ho (env, Key Vault) — hardcode kyun nahi",
    "Layered folder structure: Controller → Service → Repository → Model/DTO",
    "DTO aur loose coupling ka relation"
  ]},
  { g:"Auth aur config", items:[
    "JWT kaise kaam karta hai — header, payload, signature",
    "JWT vs Session-based auth",
    "Authentication vs Authorization",
    "Refresh token ka purpose",
    "Role-based vs Claims-based vs Policy-based authorization",
    "appsettings.json, environment-based config, IOptions pattern",
    "Logging — ILogger, structured logging, log levels"
  ]}
]},

{ id:"ef", title:"Entity Framework Core aur LINQ", note:"IQueryable vs IEnumerable ka answer galat gaya to backend round wahin khatam.", groups:[
  { g:"LINQ", items:[
    "IEnumerable vs IQueryable — memory filter vs DB SQL",
    "Deferred (lazy) execution kya hai",
    "First vs FirstOrDefault vs Single vs SingleOrDefault",
    "Where, Select, GroupBy, OrderBy, Join, Any, All, Sum, Aggregate",
    "SelectMany kab use hota hai",
    "Method syntax vs Query syntax",
    "Take, Skip — pagination ke liye",
    "Distinct, Except, Intersect, Union",
    "ToList / ToArray / ToDictionary — execution force karna",
    "Let aur multiple from clause",
    "Join vs GroupJoin vs left join in LINQ",
    "LINQ query jo DB pe translate nahi hoti — client-side evaluation ka danger"
  ]},
  { g:"EF Core", items:[
    "DbContext ka lifetime kyun Scoped hona chahiye",
    "Lazy loading vs Eager loading vs Explicit loading",
    "Include aur ThenInclude",
    "N+1 query problem — pehchanna aur fix karna",
    "AsNoTracking() kab aur kyun",
    "Change tracking kaise kaam karta hai",
    "Migrations — Add-Migration, Update-Database, rollback",
    "Code First vs Database First",
    "Raw SQL / FromSqlRaw aur stored procedure call karna",
    "EF Core vs Dapper vs ADO.NET — trade-off",
    "Transaction handling, SaveChanges ka behaviour"
  ]},
  { g:"Patterns", items:[
    "Repository pattern — fayda aur criticism",
    "Unit of Work pattern",
    "Factory, Singleton, Strategy, Mediator/CQRS ka basic idea"
  ]}
]},

{ id:"angular", title:"Angular", note:"Flow poocha jata hai: main.ts se lekar view render tak. Change detection aur RxJS pe depth chahiye.", groups:[
  { g:"Angular flow aur basics", items:[
    "Bootstrap flow: main.ts → AppModule → AppComponent → template render",
    "Component, Module, Service ka role",
    "Component lifecycle hooks — order ke saath",
    "ngOnInit vs constructor — kaam kya alag hai",
    "ngOnChanges kab trigger hota hai",
    "ngOnDestroy mein kya cleanup karte ho",
    "Data binding ke 4 types: interpolation, property, event, two-way",
    "@Input / @Output / EventEmitter — parent-child communication",
    "ViewChild aur ContentChild",
    "Directives: structural (*ngIf, *ngFor) vs attribute (ngClass, ngStyle)",
    "Custom directive banana",
    "Pipes — pure vs impure, custom pipe",
    "Angular vs AngularJS, SPA kya hota hai",
    "NgModule ke parts: declarations, imports, providers, exports, bootstrap",
    "Feature module aur Shared module ka structure",
    "Decorators kya hain (@Component, @Injectable, @NgModule)",
    "ng-template vs ng-container vs ng-content",
    "ViewEncapsulation — Emulated, ShadowDom, None",
    "@HostListener aur @HostBinding",
    "Renderer2 kyun, direct DOM access kyun nahi",
    "Angular CLI commands jo roz use hote hain",
    "TypeScript kya hai — JS ka superset, compile kaise hota hai",
    "TS types, interface vs type, generics, enum",
    "Access modifiers TypeScript mein",
    "DOM kya hai, Angular DOM ko kaise update karta hai"
  ]},
  { g:"Change detection aur performance", items:[
    "Change detection kaise kaam karti hai (Zone.js)",
    "Default vs OnPush strategy",
    "trackBy *ngFor mein kyun",
    "async pipe ka fayda",
    "Lazy loading modules",
    "AOT vs JIT compilation",
    "Preloading strategy",
    "Bundle size kam karna, tree shaking",
    "ChangeDetectorRef — markForCheck vs detectChanges",
    "Angular Universal / SSR ka basic idea"
  ]},
  { g:"RxJS", items:[
    "Observable vs Promise — difference",
    "subscribe, unsubscribe, memory leak",
    "Subject vs BehaviorSubject vs ReplaySubject",
    "map, filter, tap",
    "switchMap vs mergeMap vs concatMap vs exhaustMap",
    "debounceTime aur distinctUntilChanged (search box use case)",
    "forkJoin vs combineLatest",
    "catchError aur retry",
    "takeUntil pattern se unsubscribe"
  ]},
  { g:"Services, forms, routing", items:[
    "Service aur DI — providedIn: 'root' ka matlab",
    "HttpClient — GET/POST, error handling",
    "HttpInterceptor — JWT token attach karna",
    "Template-driven vs Reactive forms",
    "FormGroup, FormControl, FormArray, custom validator",
    "Routing — routerLink, params, queryParams",
    "Route guards: CanActivate, CanDeactivate, Resolver",
    "State management basics (service + BehaviorSubject, ya NgRx)",
    "Standalone components aur Signals (naya Angular)",
    "InjectionToken kya hai aur kab chahiye",
    "Hierarchical injector — root vs component-level provider",
    "Router events aur navigation lifecycle",
    "Dynamic component load karna",
    "Jasmine + Karma se unit test — component aur service",
    "environment.ts se environment-based config"
  ]}
]},

{ id:"postgres", title:"PostgreSQL", note:"Practical round mein laptop pe query likhwate hain. Syntax fluency chahiye, theory ke saath.", groups:[
  { g:"SQL basics aur DDL", items:[
    "DDL, DML, DCL, TCL — kaunsa command kahan",
    "Primary key vs Unique key vs Foreign key",
    "Constraints: NOT NULL, CHECK, DEFAULT, UNIQUE",
    "DELETE vs TRUNCATE vs DROP",
    "SERIAL vs IDENTITY vs Sequence",
    "Common data types + JSONB kab use karein",
    "View vs Materialized view — refresh kab karna padta hai",
    "Temp table vs CTE vs subquery",
    "Schema kya hai, search_path",
    "Roles aur GRANT/REVOKE basics",
    "ALTER TABLE — column add/drop/type change ka impact",
    "SQL vs NoSQL — kab kya choose karein",
    "Normalization (1NF, 2NF, 3NF) vs Denormalization"
  ]},
  { g:"Query writing (machine round)", items:[
    "2nd / Nth highest salary nikalna",
    "Department-wise highest salary (window function ya correlated subquery)",
    "GROUP BY + HAVING — WHERE se difference",
    "INNER / LEFT / RIGHT / FULL / CROSS JOIN — output ka farak",
    "LEFT JOIN + IS NULL se missing records dhoondhna",
    "Self join — employee aur uska manager",
    "Duplicate rows find karna aur delete karna (ctid ya ROW_NUMBER)",
    "CTE (WITH clause) se readable query",
    "Recursive CTE — hierarchy / tree traversal",
    "Subquery vs JOIN — kab kya better",
    "EXISTS vs IN vs JOIN",
    "CASE WHEN se conditional aggregation",
    "COALESCE, NULLIF, NULL handling",
    "Date functions — date_trunc, age, interval, generate_series",
    "String functions — concat, split_part, LIKE vs ILIKE",
    "UNION vs UNION ALL",
    "INSERT ... ON CONFLICT (upsert)",
    "RETURNING clause",
    "LIMIT / OFFSET pagination aur uska performance problem",
    "Keyset pagination (WHERE id > last_id)",
    "Aggregate functions: COUNT, SUM, AVG, MIN, MAX — NULL ka behaviour",
    "COUNT(*) vs COUNT(column) vs COUNT(DISTINCT)",
    "array_agg aur string_agg",
    "JSONB query karna (->, ->>, @>)"
  ]},
  { g:"Window functions", items:[
    "ROW_NUMBER vs RANK vs DENSE_RANK",
    "PARTITION BY aur ORDER BY ka role",
    "LAG aur LEAD — previous/next row compare",
    "Running total (SUM OVER)",
    "FIRST_VALUE, LAST_VALUE, NTILE"
  ]},
  { g:"Indexing aur performance", items:[
    "Index internally kaise kaam karta hai (B-tree)",
    "B-tree vs GIN vs GiST vs BRIN — kab kaunsa",
    "Composite index — column ka order kyun matter karta hai",
    "Partial index aur covering index",
    "Index kab NAHI use hota (function on column, low selectivity, type mismatch)",
    "EXPLAIN vs EXPLAIN ANALYZE padhna",
    "Seq Scan vs Index Scan vs Bitmap Heap Scan",
    "Nested Loop vs Hash Join vs Merge Join",
    "Slow query ko debug karne ka step-by-step approach",
    "Clustered vs Non-clustered index — ek table mein clustered ek hi kyun",
    "Covering index kya hai",
    "SARGable query kya hoti hai — WHERE mein column pe function lagane se index kyun mar jata hai",
    "Blocking vs Deadlock ka difference",
    "SQL Server DMV (sys.dm_exec_query_stats) se slow query dhoondhna",
    "Composite primary key — kab zaroori hoti hai"
  ]},
  { g:"Transactions aur internals", items:[
    "ACID properties — har ek ka matlab",
    "Isolation levels: Read Committed, Repeatable Read, Serializable",
    "Dirty read, non-repeatable read, phantom read",
    "MVCC kaise kaam karta hai",
    "Locks aur deadlock — kaise hota hai, kaise avoid karein",
    "VACUUM, autovacuum aur table bloat",
    "Stored procedure vs function PostgreSQL mein",
    "Trigger — kab use karein aur kab nahi",
    "Normalization (1NF–3NF) vs Denormalization",
    "Partitioning — range vs list, partition pruning",
    "Connection pooling (PgBouncer) kyun zaroori hai",
    "Replication — streaming vs logical",
    "Refcursor return karna aur .NET se consume karna",
    "Exception handling stored procedure ke andar",
    "COMMIT / ROLLBACK / SAVEPOINT",
    "pg_stat_activity se running query dekhna aur kill karna",
    "pg_dump / pg_restore se backup aur restore",
    "Foreign Data Wrapper (FDW) kya hai",
    "Deadlock ka real example aur uska fix"
  ]}
]},

{ id:"resume", title:"Tumhare resume ke deep-dive topics", flagged:true, note:"Resume pe Kafka, Redis, Tile38, TCP likha hai — interviewer yahin sabse zyada drill karega. Har answer mein apne project ka concrete number ya decision hona chahiye.", groups:[
  { g:"Kafka", items:[
    "Producer, Broker, Consumer, Topic, Partition, Offset",
    "Consumer group aur rebalancing",
    "Partition key kaise choose ki — ordering guarantee kaise mili",
    "At-least-once vs at-most-once vs exactly-once",
    "Duplicate processing kaise handle kiya (idempotency)",
    "Consumer lag badhne pe kya karoge",
    "Retention aur log compaction",
    "Kafka vs RabbitMQ — kab kya"
  ]},
  { g:"Redis", items:[
    "Data structures: string, hash, list, set, sorted set",
    "Redis kyun, direct DB kyun nahi — apne case mein justify karo",
    "Cache-aside vs write-through vs write-behind",
    "TTL aur eviction policies (LRU, LFU)",
    "Cache invalidation strategy tumhare project mein kya thi",
    "Pub/Sub vs Streams",
    "Persistence: RDB vs AOF",
    "Redis kab galat choice hai"
  ]},
  { g:"TCP / GPS device panel", items:[
    "TCP stream-based hai — message boundary kaise define ki (framing)",
    "Partial packet aur packet coalescing handle karna",
    "Multiple firmware variants ka parsing — design kya rakha",
    "Thread safety — shared state kahan tha aur kaise protect kiya",
    "Connection drop aur reconnection handling",
    "Backpressure — device fast, processing slow ho to kya"
  ]},
  { g:"Tile38 aur geo", items:[
    "Geofencing concept — WITHIN, NEARBY, INTERSECTS",
    "Tile38 kyun, PostGIS kyun nahi",
    "Geo indexing kaise hoti hai",
    "Stop-arrival detection ka logic"
  ]},
  { g:"SignalR", items:[
    "SignalR kaise kaam karta hai (WebSocket, fallback transports)",
    "Multiple server instances pe scale — Redis backplane",
    "Hub, group, connection management",
    "DB trigger se app tak signal kaise pahuncha (NOTIFY/LISTEN)",
    "WebSocket vs SSE vs Long Polling"
  ]},
  { g:"Apna system explain karna", items:[
    "AVLS ka end-to-end data flow 3 minute mein whiteboard pe",
    "Scale ke numbers: kitne vehicles, kitne packets/sec, DB size",
    "Sabse bada bottleneck kya tha aur kaise solve kiya",
    "Agar 10x traffic aa jaye to kya todega",
    "Ek design decision jo galat tha aur ab kya alag karte"
  ]}
]},

{ id:"web", title:"Web aur networking fundamentals", note:"Service company screening rounds mein yeh sab rapid-fire aata hai.", groups:[
  { g:"HTTP aur web", items:[
    "HTTP request/response structure",
    "HTTP methods aur idempotency",
    "Status code families — 2xx, 3xx, 4xx, 5xx",
    "HTTP/1.1 vs HTTP/2",
    "Cookies, sessions, localStorage vs sessionStorage",
    "CORS aur preflight request",
    "URL type karne se page render tak kya hota hai"
  ]},
  { g:"Security", items:[
    "Hashing vs Encryption vs Encoding",
    "Salting kyun zaroori hai, bcrypt",
    "OAuth 2.0 aur OpenID Connect ka basic flow",
    "Keycloak / IDAM ka role",
    "SQL Injection, XSS, CSRF — aur unka bachav",
    "SSL/TLS handshake, HTTPS kaise secure hai",
    "Rate limiting aur DDoS protection",
    "Webhook vs Web service / API"
  ]}
]},

{ id:"devops", title:"DevOps aur infrastructure", note:"Yeh tumhara edge hai — zyadatar candidates yahan blank hote hain.", groups:[
  { g:"Git", items:[
    "clone, pull, fetch, add, commit, push — basic flow",
    "Branch banana, checkout, switch",
    "Merge vs Rebase — history pe kya farak",
    "Merge conflict resolve karna",
    "git stash, git reset vs git revert",
    "Cherry-pick kab use karte ho",
    "Pull Request flow aur acchi PR description",
    "Branching strategy (feature branch, develop, main)"
  ]},
  { g:"Agile, SDLC aur process", items:[
    "SDLC ke phases: Requirement → Planning → Design → Development → Testing → Deployment → Maintenance",
    "Waterfall vs Agile",
    "Scrum — sprint, sprint planning, daily standup, retrospective",
    "Scrum Master, Product Owner, team ka role",
    "Daily standup mein kya bolte ho (kal kya kiya, aaj kya, blocker)",
    "JIRA / ticket workflow",
    "Code review mein kya dekhte ho",
    "Onshore-offshore team ke saath communication",
    "Unit test vs Integration test vs System test"
  ]},
  { g:"Containers aur CI/CD", items:[
    "Docker image vs container",
    "Dockerfile, layers, multi-stage build",
    "docker-compose se multi-container setup",
    "Volume aur network basics",
    "Container vs VM",
    "CI/CD pipeline ke stages — Jenkins ya GitLab CI",
    "Build, test, deploy automation ka flow"
  ]},
  { g:"Linux aur server", items:[
    "Rozmarra commands: grep, awk, sed, find, ps, top, df, netstat/ss",
    "Log dekhna — tail -f, journalctl",
    "File permissions aur chmod/chown",
    "systemd service manage karna",
    "Nginx reverse proxy — config aur kyun chahiye",
    "curl se API test karna",
    "SSL certificate install aur renew",
    "Server slow hai — debug karne ka order"
  ]},
  { g:"Cloud aur monitoring", items:[
    "GCP Compute Engine instance kya hai, VPC aur firewall rules",
    "Load balancer ka kaam",
    "Horizontal vs Vertical scaling",
    "Kibana / ELK se log search",
    "Monitoring aur alerting ka basic setup",
    "Cloud computing kya hai, companies kyun use karti hain",
    "IaaS vs PaaS vs SaaS, Serverless kya hai",
    "Azure App Service, Azure Functions, Blob Storage, Azure SQL DB, Service Bus",
    "Azure DevOps — build pipeline vs release pipeline, artifacts",
    "AWS equivalents: EC2, S3, RDS, Lambda",
    "Cloud mein secrets rakhna — Azure Key Vault / AWS Secrets Manager",
    "Deployment flow: code push → build → test → artifact → QA → production"
  ]}
]},

{ id:"design", title:"System design (basic level)", note:"Tumse FAANG-level design nahi chahiye. Thinking chahiye. Apna AVLS system hi best answer hai.", groups:[
  { g:"Concepts", items:[
    "Monolith vs Microservices — trade-offs",
    "Load balancing aur health checks",
    "Caching layers kahan-kahan lagti hain",
    "Database replication aur sharding",
    "CAP theorem",
    "Event-driven architecture",
    "API Gateway ka role",
    "Circuit breaker aur retry with backoff",
    "Synchronous vs Asynchronous communication"
  ]},
  { g:"Design practice", items:[
    "Real-time vehicle tracking system (tumhara apna — sabse strong)",
    "Notification service",
    "URL shortener",
    "Rate limiter"
  ]}
]},

{ id:"coding", title:"Practical / machine round coding", note:"Ahmedabad mein aksar laptop deke bolte hain — likhna aana chahiye, sirf bolna nahi.", groups:[
  { g:"C# coding problems", items:[
    "String reverse — built-in ke bina",
    "Palindrome check",
    "Anagram check",
    "String mein first non-repeating character",
    "Array mein duplicates find karna",
    "Array mein second largest number",
    "FizzBuzz aur uske variants",
    "Factorial / Fibonacci — loop aur recursion dono",
    "Prime number check",
    "Two sum",
    "Sentence mein word frequency count (Dictionary)",
    "List of objects ko LINQ se group aur sort karna",
    "Employee list se department-wise max salary — LINQ mein",
    "String mein vowels/characters count",
    "Sentence mein words reverse karna",
    "Array rotate karna",
    "Missing number in array 1..n",
    "Two arrays ka common element",
    "Matrix / 2D array traversal",
    "Sorted array mein binary search",
    "Bubble sort ya selection sort hath se likhna",
    "Linked list reverse (agar DSA round hai)",
    "Sum of digits / Armstrong / perfect number type basics",
    "Reverse a number (digit by digit, while loop)",
    "Palindrome number check",
    "Swap two numbers — temp ke saath aur bina temp ke",
    "Largest number in array (foreach + max)"
  ]},
  { g:"Round ke doosre parts", items:[
    "Ek chhota CRUD Web API 30 minute mein bana lena",
    "Diya hua SQL slow hai — optimize karke dikhana",
    "Diya hua code review karna aur bugs batana",
    "Angular mein chhota component + service + HTTP call"
  ]}
]},

{ id:"hr", title:"HR aur behavioural", note:"Technical clear karke yahan reject hona sabse mehenga hai. Answers likh ke rakho.", groups:[
  { g:"Ready rakho", items:[
    "Apna introduction — 90 second, structured",
    "Company chhodne ka reason (blame-free version)",
    "Sabse challenging technical problem jo solve kiya",
    "Production issue jo tumne debug kiya — step by step",
    "Ek galti jo hui aur usse kya seekha",
    "Team conflict ya disagreement kaise handle kiya",
    "Strength aur weakness — honest aur specific",
    "Agle 3 saal ka plan",
    "Current aur expected CTC — number ready rakho",
    "Notice period aur joining date",
    "Interviewer se poochhne ke liye 3 sawaal"
  ]}
]}
];

const CHEAT = [
{g:"ASP.NET Core — pipeline", items:[
["app.Use","Middleware jodta hai. Apna kaam karke **`next()`** se request aage bhejta hai."],
["app.Run","**Terminal** middleware — `next()` nahi bulata, pipeline yahin khatam."],
["app.Map","**Path ke hisaab se branch** — `/admin` wali requests alag pipeline mein."],
["Custom middleware","Har request pe chalne wala apna code — **logging, correlation ID, error handling**."],
["Global exception handling","**Ek jagah saare errors pakdo** aur same format mein lautao (status + message). `UseExceptionHandler` / `IExceptionHandler`."],
["ASP.NET Core request pipeline","Request → **middlewares (order mein)** → routing → controller → response wapas usi raaste."],
["MVC request lifecycle","Request → **Routing** → Controller → **Action** → Model/data → **Result** (View/JSON) → Response."],
["Filters (MVC)","Action ke **pehle/baad** chalte hain. Order: **Authorization → Resource → Action → Exception → Result**."],
["Action result types","`Ok()`, `NotFound()`, `BadRequest()`, `CreatedAtAction()`, `View()`, `Json()`, `File()`, `Redirect()`."],
["Common status codes","**200** OK · **201** Created · **204** No Content · **400** Bad Request · **401** login nahi · **403** permission nahi · **404** Not Found · **500** server error."],
["Web API","HTTP pe **data (JSON) dene wali service** — Angular, mobile app use karte hain. HTML nahi deti."],
["Swagger","API ka **auto documentation + browser se test** karne ka page (OpenAPI)."],
["Web API optimize karna","**async**, **caching**, **pagination**, DTO (kam data), **DB index**, N+1 hatao, compression."],
["Large result handling","**Pagination** — `page` + `pageSize` lo, data ke saath **total count** lautao."],
["Third-party API call","**`IHttpClientFactory`** / typed client (DI se). Timeout + retry, error handle, API key header mein."],
["Background hosted service","Request ke bahar chalne wala kaam — **`BackgroundService`** (scheduled jobs, queue processing)."],
["Caching","Baar-baar padha jaane wala data **memory/Redis** mein — DB pe load kam, response tez."],
["CORS","Browser ka rule: **doosre domain ki API call** tabhi jab server allow kare (`Access-Control-Allow-Origin`)."],
["Serialization / Deserialization","**Object → JSON** = serialization. **JSON → object** = deserialization. (`System.Text.Json`)"],
["ViewData","Controller → View data. **Dictionary**, string key, casting chahiye."],
["ViewBag","ViewData ka **dynamic** version — `ViewBag.Name`, casting nahi."],
["TempData","**Redirect ke baad** bhi data rehta hai — ek baar padhne pe hat jaata hai."],
["HTML Helper","Razor mein C# se HTML banana — `Html.TextBoxFor()`. Naya tareeka: **Tag Helpers** (`asp-for`)."],
["DTO","**Data Transfer Object** — API mein sirf zaroori fields bhejo, poori DB entity nahi."],
["Loose coupling","Classes **interface pe depend** karein, concrete class pe nahi (DI se) — badlav aur testing aasan."],
["Folder structure","**Controller → Service → Repository → DB**. Models/DTOs, Interfaces alag folder."],
["Version matrix","Apna **exact version** yaad rakho: .NET (8/6), Angular, SQL/PostgreSQL, Visual Studio."]
]},
{g:"C# — core", items:[
["Class","**Blueprint** — object kaisa hoga uska design. Jaise `Booking` class."],
["Object","Class ka **asli instance** memory mein — `new Booking()`."],
["Interface","Sirf **contract** (kya karna hai). Ek class **kai interfaces** implement kar sakti hai."],
["Abstract class","**Adhoori class** — kuch methods ready, kuch abstract. `new` nahi kar sakte, **sirf ek** inherit hoti hai."],
["Abstract class kab","Jab **common code share** karna ho — jaise saare payments ka common logic `PaymentBase` mein."],
["Interface kab","Jab sirf **behaviour/capability** batani ho — `IPayable.Pay()` — alag classes alag tareeke se karein."],
["Access modifiers","**public** sab · **private** sirf class · **protected** class + child · **internal** same project · **protected internal** dono."],
["Constructor","`new` karte hi **automatically chalne wala method** — object set up karta hai."],
["try / catch / finally","**try** risky code · **catch** error sambhalo · **finally** hamesha chalta hai (cleanup)."],
["Synchronous","Kaam **poora hone tak ruko**, phir agla."],
["Asynchronous","Kaam shuru karo, **wait mein thread free** — `async/await`. I/O (DB, API) ke liye."],
["Dependency Injection","Class apni dependency **khud `new` nahi karti, bahar se milti hai** (constructor). Loose coupling + testing."],
["CLR","**Common Language Runtime** — .NET code chalata hai: JIT, **GC**, exceptions, security."],
["CTS","**Common Type System** — saari .NET languages ke **common types** (C# `int` = VB `Integer` = `System.Int32`)."],
["CLS","**Common Language Specification** — rules taaki ek language ki library doosri use kar sake."],
["Repository pattern","**DB ka code ek class mein** — business logic ko pata nahi data kahan se aaya. Testable."],
["First() vs FirstOrDefault()","Na mile to **`First()` exception**, **`FirstOrDefault()` null/default**."],
["Single() vs SingleOrDefault()","**Bilkul ek** chahiye. Zero pe: `Single()` exception, `SingleOrDefault()` null. **Ek se zyada = dono exception**."],
["LINQ — highest salary","Highest: `emps.Max(e => e.Salary)`. **2nd highest**: `.Select(x => x.Salary).Distinct().OrderByDescending(x => x).Skip(1).FirstOrDefault()`."],
["REST API design","**Resource naam** (`/api/orders`), **HTTP verbs** (GET/POST/PUT/DELETE), sahi status codes, validation, DTOs."]
]},
{g:"SQL aur performance", items:[
["SQL Index","**Kitaab ke index** jaisa — poori table padhe bina seedha row tak. Reads tez, writes thode slow."],
["Clustered index","**Table ka data isi order mein** stored. Table mein **sirf ek** (aksar primary key)."],
["Non-clustered index","**Alag structure** jo row ka pointer rakhta hai. **Kai** ho sakte hain."],
["Covering index","Index mein query ke **saare columns** (`INCLUDE`) — table pe jaana hi nahi padta."],
["SARGable query","Jo **index use kar sake**. `WHERE date >= '2026-09-06'` ✔ · `WHERE YEAR(date) = 2026` ✘ (column pe function)."],
["Blocking","Ek transaction ne lock rakha, doosra **wait** kar raha hai. Temporary — pehla khatam, doosra chalega."],
["Deadlock","Do transactions **ek doosre ka wait** — koi aage nahi. DB ek ko **victim** bana ke kill karta hai."],
["DMV","SQL Server ke **monitoring views** — `sys.dm_exec_query_stats` se slow queries. (PostgreSQL: `pg_stat_statements`)"],
["N+1 problem","1 query list ke liye + **har row ke liye 1 aur** = 101 queries. Fix: **`Include()` / JOIN / projection**."],
["SQL Injection","User input **SQL ka hissa ban jaata hai**. Bachav: **parameterized queries** / EF LINQ, string jodna kabhi nahi."],
["WHERE clause","**Rows filter** karta hai — SELECT, UPDATE, DELETE mein."],
["SELECT statement clauses","Likhne ka order: **SELECT · FROM · JOIN · WHERE · GROUP BY · HAVING · ORDER BY · LIMIT/TOP**."],
["Composite primary key","**Do+ columns milke unique** — `(StudentID, CourseID)`."],
["Entity Framework","**ORM** — SQL ki jagah **C# objects/LINQ** se DB ka kaam. Migrations, change tracking."],
["Dapper","**Micro-ORM** — SQL khud likho, result object mein map. **EF se tez**, features kam."]
]},
{g:"Angular", items:[
["Angular","Google ka **TypeScript framework** — SPA banane ke liye. Components, routing, DI, forms, HTTP sab built-in."],
["Main features","**Components**, data binding, **DI**, routing, forms, **RxJS**, CLI, TypeScript."],
["Component","UI ka **building block** = **template (HTML) + class (TS) + style (CSS)**."],
["Module","Related cheezon ka **group** (`NgModule`). Naye Angular mein **standalone components** — module zaroori nahi."],
["Data binding","`{{ }}` interpolation · `[prop]` property · `(event)` event · `[(ngModel)]` **two-way**."],
["One-way vs Two-way","**One-way** = data ek taraf (saaf, debug aasan). **Two-way** = UI ↔ class dono taraf sync (forms)."],
["Directive","DOM ka **behaviour/structure badalti** hai. **Component**, **Structural** (`*ngIf`), **Attribute** (`ngClass`)."],
["ngIf / ngFor","**`*ngIf`** dikhao/hatao · **`*ngFor`** loop. Naya syntax: **`@if` / `@for`** (track zaroori)."],
["Dependency Injection","Angular **services khud inject** karta hai — constructor ya `inject()` se."],
["Routing","URL → component. `{ path: 'home', component: HomeComponent }`. **Lazy loading**, **guards**."],
["Pipe","Template mein **display ke liye value badlo** — `date`, `currency`, `uppercase`, `async`."],
["Custom pipe","Apna transform — `@Pipe` + `transform()`. **Pure** pipe = input badle tabhi chale (tez)."],
["Observable","**Values ki stream** (0, 1 ya bahut). **Lazy** (subscribe pe chale), **cancel** ho sakta hai."],
["Promise","**Ek hi value**, turant chalta hai, cancel nahi hota."],
["Component communication","Parent → child **`@Input`** · child → parent **`@Output` + EventEmitter** · door wale → **shared service**."],
["Interceptor","**Har HTTP call ke beech** — token lagao, errors pakdo, loader dikhao."],
["AOT","**Ahead-of-Time** — templates **build pe compile**. Load tez, bundle chhota, template errors pehle pakde."],
["Angular lifecycle","**constructor → ngOnChanges → ngOnInit → … → ngOnDestroy**."],
["ngOnInit","Inputs set hone ke baad **ek baar** — **API call / setup yahin**."],
["ngOnDestroy","Component hatne se pehle — **unsubscribe, timers clear** (memory leak rokne ke liye)."],
["RxJS","**Observables ki library** — `map`, `filter`, **`switchMap`**, `debounceTime`, `catchError`."],
["ViewChild","Parent se **child component / DOM element ka reference** — `@ViewChild`. `ngAfterViewInit` ke baad milta hai."],
["SPA","**Single Page Application** — ek page load, phir sirf content badalta hai, **reload nahi**."],
["TypeScript","**JavaScript + types** (Microsoft). Compile pe errors pakdo, phir JS banta hai."],
["DOM","**HTML ka tree** jo browser memory mein banata hai — JS/Angular isko badalte hain."],
["Template","Component ka **HTML view** — bindings aur directives ke saath."],
["Event binding","**`(click)=\"save()\"`** — user action pe method chalao."],
["Interpolation","**`{{ name }}`** — class ki value HTML mein text ki tarah."],
["Decorator","**`@` wala metadata** — `@Component`, `@Injectable`, `@Input` — Angular ko batata hai class kya hai."],
["Property binding","**`[src]=\"imgUrl\"`** — class ki value element ki property mein."]
]},
{g:"Cloud, DevOps, Agile", items:[
["Cloud computing","Apna server kharidne ki jagah **internet pe kiraye ke resources** — server, storage, DB."],
["Cloud kyun use karte hain","**Scale** up/down, **jitna use utna pay**, tez setup, **managed** backups/security."],
["Azure Functions","**Serverless** — sirf function likho, server/scaling Azure ka. Event pe chalta hai (order → invoice mail)."],
["Azure App Service","Web app / API host karne ka **PaaS** — OS/patching Azure ka."],
["Azure Storage / Blob","**Files, images, backups** rakhne ki cloud storage. (AWS: **S3**)"],
["Azure SQL DB","Microsoft ka **managed SQL Server** cloud mein."],
["Azure Service Bus","**Message queue/topics** — apps ke beech async communication. (AWS: SQS/SNS)"],
["AWS equivalents","**EC2** = VM · **S3** = file storage · **RDS** = managed DB · **Lambda** = serverless · **SQS** = queue."],
["API Gateway","Saari services ka **ek entry gate** — routing, auth, rate limit ek jagah."],
["Docker","App ko **dependencies ke saath package** (image) — har jagah same chale."],
["Container","Image ka **chalta hua instance** — halka, isolated process."],
["Container vs VM","**VM = poora OS** (GBs, minutes). **Container = host ka kernel share** (MBs, seconds)."],
["DevOps","**Dev + Ops saath** — automation (CI/CD), monitoring, jaldi aur safe releases."],
["Azure DevOps","**Repos + Pipelines (CI/CD) + Boards (tickets)** — ek platform."],
["Build pipeline","**CI** — push pe code **compile + tests + artifact** banana."],
["Release pipeline","**CD** — artifact ko **Dev → QA → Prod** pe deploy (approval ke saath)."],
["Deployment flow","**Push → build → tests → artifact → QA deploy → approval → Prod**."],
["Version control","Code ke **har change ka record** — team saath kaam kare, purana version wapas la sako (Git)."],
["Git commands","`clone` · `pull` · `checkout -b` · `add` · `commit` · `push` · `merge` · `rebase` · `stash`."],
["Merge","Branches jodta hai **merge commit** bana ke — history **jaisi thi waisi** rehti hai."],
["Rebase","Apne commits ko **doosri branch ke upar dobara** lagata hai — history **seedhi line**. Shared branch pe mat karo."],
["Logging","App ke events/errors ka **record** — debugging + monitoring. Structured logs (**Serilog**)."],
["Connection string management","**Code mein kabhi nahi**. Dev: user-secrets · Prod: **env variables / Key Vault**."],
["Environment variable","Code ke **bahar rakhi setting** — har environment mein alag value."],
["SDLC","**Requirement → Design → Development → Testing → Deployment → Maintenance**."],
["Agile","Kaam **chhote sprints** mein, har sprint ke baad working software + **feedback**."],
["Scrum","Agile framework. **PO** (kya banana), **Scrum Master** (process), **Team**. Planning · Daily standup · Review · Retro."],
["Daily standup","15 min: **kal kya kiya, aaj kya karunga, koi blocker?**"],
["Onshore / offshore","Alag timezone ki team — **clear likhit communication**, decisions document, detailed PRs, overlap hours mein calls."],
["Unit test","**Ek class/method akele** test — dependencies mock."],
["Integration test","**Kai hisse saath** — API + asli DB."],
["System test","**Poori app end-to-end**, user ki tarah."],
["Monolith","**Ek hi deployable app** — shuru mein simple, bada hone pe scale/deploy mushkil."],
["Microservices","**Chhoti alag services** (user, order, payment) — alag deploy/scale. Keemat: **complexity**."]
]},
{g:"Coding — ratne wale snippets", items:[
["Fibonacci","`a=0, b=1;` loop: `(a, b) = (b, a + b);` — **recursion bina memo = O(2ⁿ)**, loop O(n)."],
["Prime number","n < 2 → nahi. **i = 2 se √n tak** (`i * i <= n`) — `n % i == 0` mila to prime nahi."],
["Largest number","**`max = arr[0]`** (0 se nahi!) → foreach: `if (x > max) max = x;`"],
["Second largest","`first`, `second`. x > first → **second = first, first = x**. Warna x > second **aur x != first** → second = x."],
["Remove duplicates","**`HashSet`** mein daalo, ya LINQ **`arr.Distinct()`**."],
["Reverse string","**Two pointers** swap `char[]` mein — ya `new string(s.Reverse().ToArray())`."],
["Reverse number","Loop: `rev = rev * 10 + n % 10; n /= 10;` — **overflow** ka dhyan."],
["Palindrome number","Number reverse karke **original se compare**. Negative = palindrome nahi."],
["Swap two numbers","`(a, b) = (b, a);` — ya temp. Bina temp: `a = a + b; b = a - b; a = a - b;`"],
["FizzBuzz","**15 wala check pehle** (`i % 15 == 0`), phir 3 → Fizz, 5 → Buzz, warna number."]
]},
{g:"Asli poochhe gaye — C# / .NET", items:[
["Components of .NET","**CLR** (runtime) · **CTS** (types) · **CLS** (rules) · **BCL** (libraries) · languages (C#, F#, VB)."],
["FCL vs BCL","**BCL** = core classes (`System`, collections, IO). **FCL** = poori library (BCL + ASP.NET, EF…)."],
["Type safety","Variable mein **sirf uske type ka data** — galat type pe **compile error**."],
["Stack vs Heap","**Stack**: local value types, method khatam = saaf. **Heap**: objects (reference types) — **GC saaf karta hai**."],
["GC kaise kaam karti hai","**Gen 0** (naye) → **Gen 1** → **Gen 2** (lambe). Jo object ab **reachable nahi**, uski memory free."],
["Sealed class","**Inherit nahi** ho sakti — `sealed`. (`string` sealed hai.)"],
["Partial class","Ek class **kai files mein** — compile pe jud jaati hai. Generated code ke saath."],
["Types of classes","**Static · Abstract · Sealed · Partial · Generic · Nested** (+ record)."],
["Constructor inheritance mein","**Pehle base ka constructor**, phir child ka. Parameters: `: base(x)`."],
["Multiple inheritance C# mein","Classes se **nahi** (diamond problem). **Kai interfaces** se ho jaata hai."],
["A, B, C, D ki property Z mein bina inheritance/interface","**Composition** — Z ke andar A, B, C, D ke objects as properties (**has-a**, is-a nahi)."],
["readonly vs static","**readonly**: constructor ke baad badal nahi sakti, **har object ki alag**. **static**: **class ki ek hi copy**, sab share karte hain."],
["const vs readonly","**const**: compile-time, hamesha static, value fix. **readonly**: runtime pe constructor mein set."],
["Pass by value vs reference","Default **copy** jaati hai. **`ref` / `out`** = original variable hi badalta hai."],
["Dispose vs Finalize","**Dispose**: tum bulate ho (`using`), turant cleanup. **Finalize**: GC bulata hai, **kab pata nahi**."],
["Types of exceptions","System: **NullReference, DivideByZero, IndexOutOfRange, InvalidOperation**. Plus **custom** (`: Exception`)."],
["Finally catch ke baad chalta hai?","**Haan, hamesha** — exception aaye ya na aaye, `return` ho tab bhi."],
["IList vs IEnumerable","**IEnumerable**: sirf loop (aage-aage). **IList**: index, Add, Remove bhi."],
["Lambda expression","**Chhota anonymous function** — `x => x.Salary > 50000`. LINQ mein."],
["Authentication vs Authorization","**Authentication** = tum kaun ho (login, 401). **Authorization** = kya kar sakte ho (permission, 403)."],
[".NET Core mein authentication","**JWT** (APIs), cookies, ya Identity. `AddAuthentication().AddJwtBearer()` · order: **`UseAuthentication()` phir `UseAuthorization()`**."],
["API key authentication ke tareeke","Header se key padho aur check karo — **middleware**, **custom AuthenticationHandler** ya **filter**."],
["Program.cs vs Startup.cs","Purane: **Startup.cs** (ConfigureServices + Configure). **.NET 6+**: sab **Program.cs** mein (minimal hosting)."],
["MVC action methods","**ViewResult, PartialViewResult, JsonResult, RedirectResult, RedirectToActionResult, FileResult, ContentResult, StatusCodeResult**."],
["Action Filter","Action ke **pehle/baad** code — logging, validation, timing. `OnActionExecuting` / `OnActionExecuted`."],
["Attribute routing","Route **seedha upar likho** — `[Route(\"api/orders/{id}\")]`, `[HttpGet(\"{id}\")]`."],
["Ek view se doosre view pe redirect","**`return RedirectToAction(\"Action\", \"Controller\");`** — ya `return View(\"OtherView\")`."],
["TempData view mein use ho sakta hai?","**Haan**. Redirect ke baad bhi milta hai, **ek baar padhne pe hat jaata** hai (`Keep()` / `Peek()` se rakho). Core mein default cookie mein."],
["State management","Client: **cookie, query string, hidden field, localStorage**. Server: **Session, TempData, Cache**."],
["Web API vs Web Service","**Web Service (SOAP)**: XML, heavy, WSDL. **Web API (REST)**: JSON, halka, koi bhi HTTP client."],
["URL vs URN","**URL** = kahan hai (address). **URN** = naam/identity (jaise ISBN), location nahi."],
["200 status code se success message","**Haan** — `200` + body mein message. Naya resource bana to **201 Created** better."],
["SOLID","**S** ek class ek kaam · **O** extend karo, modify nahi · **L** child parent ki jagah chale · **I** chhote interfaces · **D** abstraction pe depend."],
["Software architecture","App ka **overall structure** — layers (UI, Business, Data), unka connection, pattern (Monolith, Microservices, Clean)."]
]},
{g:"Asli poochhe gaye — SQL", items:[
["varchar vs nvarchar","**varchar** = non-Unicode (1 byte). **nvarchar** = **Unicode** (2 bytes) — Hindi/multi-language."],
["varchar2","**Oracle** ka type — SQL Server mein nahi hota."],
["# vs ## temp table","**`#temp`** = sirf **meri session**. **`##temp`** = **sab sessions** ko dikhta hai."],
["Primary key vs Composite primary key","**PK** = ek column se unique. **Composite** = **do+ columns milke** unique."],
["6th highest salary","**`DENSE_RANK() OVER (ORDER BY Salary DESC)`** = 6 — ya `ORDER BY Salary DESC OFFSET 5 ROWS FETCH NEXT 1 ROWS ONLY` (DISTINCT ke saath)."],
["OFFSET","**Kitni rows skip** — `OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY` = page 2. Pagination."],
["10 dependent inserts, 9th pe error","**Transaction** + TRY/CATCH — error pe **ROLLBACK**. Ya sab insert, ya kuch nahi."],
["SQL mein exception handling","**`BEGIN TRY … END TRY BEGIN CATCH … END CATCH`** · `ERROR_MESSAGE()` · `THROW`."],
["Transaction, Commit, Rollback","**Transaction** = ek unit. **COMMIT** = pakka save. **ROLLBACK** = sab undo."],
["ACID","**A**tomic (sab ya kuch nahi) · **C**onsistent · **I**solated · **D**urable (commit ke baad safe)."],
["Normalization","**Duplicate data hatao**. **1NF** ek cell ek value · **2NF** poori key pe depend · **3NF** non-key pe depend nahi."],
["Types of joins","**INNER** match · **LEFT** left ki sab · **RIGHT** · **FULL** dono ki sab · **CROSS** har row × har row · **SELF** khud se."],
["Cross join","**Har row × har row** — 10 × 10 = **100 rows**."],
["UPDATE mein join","`UPDATE o SET o.Status = 'X' FROM Orders o JOIN Customers c ON o.CustId = c.Id WHERE …`"],
["DELETE mein join","`DELETE o FROM Orders o JOIN Customers c ON o.CustId = c.Id WHERE c.Active = 0`"],
["UNION vs UNION ALL","**UNION** duplicates hatata hai (slow). **UNION ALL** sab rakhta hai (**tez**)."],
["INTERSECT","**Dono queries mein common** rows."],
["HAVING vs WHERE","**WHERE** = grouping se pehle rows. **HAVING** = GROUP BY ke baad groups (`COUNT(*) > 5`)."],
["Aggregate functions","**COUNT, SUM, AVG, MIN, MAX** — NULL ignore (**`COUNT(*)` nahi**)."],
["Cursor","**Row-by-row** processing — **slow**, aakhri option. Set-based query better."],
["Trigger","INSERT/UPDATE/DELETE pe **apne aap chalne wala code** — audit log."],
["Stored procedure","DB mein **saved SQL** — reusable, plan cache, parameters se safe, permissions."],
["View","**Saved query = virtual table**. Complexity chhupao, security. Indexed/materialized view data store karta hai."],
["Scalar-valued function","**Ek value** lautata hai — `SELECT dbo.GetAge(@dob)`."],
["Table-valued function","**Table lautata hai** — `FROM` mein use karo."],
["Function vs Stored procedure","**Function**: value lautaye, SELECT mein chale, **data change nahi**. **SP**: INSERT/UPDATE, transactions, SELECT ke andar nahi."],
["MERGE","Ek statement mein **INSERT + UPDATE + DELETE** — **upsert** ke liye."],
["Indexing ka purpose","**Search tez** — full scan ki jagah seedha row. Keemat: writes slow, extra space."],
["Types of index","**Clustered** (ek) · **Non-clustered** (kai) · **Unique** · **Composite** · **Filtered** · **Covering**."],
["OLTP vs OLAP","**OLTP** = roz ke transactions, chhote read/write. **OLAP** = reports/analysis, bade aggregates."],
["NULL handle karna SELECT mein","**`ISNULL(col, 0)`** / **`COALESCE(a, b, 0)`**. Check: **`IS NULL`**, `= NULL` kabhi nahi."],
["Dapper","**Micro-ORM** — SQL khud likho, tez. Reports/dashboards ke liye."]
]},
{g:"Asli poochhe gaye — Angular / JS / jQuery", items:[
["@Component decorator","Class ko **component banata** hai — `selector`, `templateUrl`, `styleUrls`."],
["Constructor vs ngOnInit","**Constructor**: sirf **DI**. **ngOnInit**: inputs ready — **API call yahan**."],
["main.ts / app.module","**main.ts** = entry point, app **bootstrap** karta hai. Root: `AppModule` / standalone `AppComponent`."],
["ng serve pe kaunsi class start hoti hai","**main.ts** → bootstrap → **`AppComponent`** pehle render."],
["Angular code browser kaise samajhta hai","**TS + templates → JavaScript** (Angular compiler), bundle banta hai, browser JS chalata hai."],
["Filter Angular mein","Angular 2+ mein filter pipe nahi — **`array.filter()`** ya **custom pipe**."],
["Service Angular mein","**`@Injectable`** class — shared logic + API calls. `providedIn: 'root'` = **singleton**."],
["ng-app","**AngularJS (1.x)** ka root directive. Naye Angular mein nahi."],
["Directives (AngularJS)","**ng-app, ng-model, ng-repeat, ng-if, ng-show/hide, ng-click**."],
["var vs let","**var**: function-scope, hoist hoke `undefined`. **let**: **block-scope**, pehle use = error."],
["JS mein variable define karne se pehle use","**var** → `undefined` (hoisting). **let/const** → **ReferenceError**."],
["null vs undefined","**undefined** = value di hi nahi. **null** = jaan-boojh ke khaali."],
["== vs ===","**`==`** type badal ke compare (`0 == false` true). **`===`** type + value — **hamesha yahi**."],
["filter() vs find()","**filter()** = saare matches (array). **find()** = **pehla** match (ya undefined)."],
["setTimeout vs setInterval","**setTimeout** = ek baar. **setInterval** = baar-baar (`clearInterval` se roko)."],
["atob() / btoa()","JS functions: **`btoa()`** encode to Base64, **`atob()`** decode."],
["jQuery kya hai","**JS library** — DOM, events, AJAX aasan. `$('#id')`."],
["jQuery events","`click, change, submit, keyup, focus, blur` — `$('#btn').on('click', fn)`."],
["JavaScript vs TypeScript","**TS = JS + types**, compile-time errors. Browser mein chalne se pehle **JS mein compile**."]
]},
{g:"Apne project ke baare mein (khud tayyar karo)", items:[
["Current project ki architecture","**3 minute** mein whiteboard pe: layers, services, DB, queue, flow. **Note mein likh ke rakho**."],
["Current project ka domain","**Ek line**: kya problem, users kaun, business value."],
["Current project ka framework aur version","**Exact** .NET, Angular, DB version — atakna nahi chahiye."],
["Technical challenge","**STAR**: kya toota, kaise debug kiya, kya fix, **result numbers ke saath**."],
["Team aur process","Team size, **sprint length**, code review, deploy kaun/kaise karta hai."]
]}
];
